import type { NextConfig } from "next";
import path from "path";
import { REDIRECTS } from "./src/data/redirects";

const nextConfig: NextConfig = {
  // Keep Turbopack scoped to this app — a parent ~/package-lock.json otherwise
  // makes Tailwind scan the whole home directory (and pick up broken live-site paths).
  turbopack: {
    root: path.join(__dirname),
  },
  allowedDevOrigins: ["127.0.0.1", "localhost"],
  images: {
    // Vercel hobby/free image optimization returns 402
    // (OPTIMIZED_IMAGE_REQUEST_PAYMENT_REQUIRED). Serve public/
    // assets directly so images work in production.
    unoptimized: true,
    loader: "custom",
    loaderFile: "./src/lib/imageLoader.ts",
    remotePatterns: [
      {
        protocol: "https",
        hostname: "vmls.edu.in",
        pathname: "/**",
      },
    ],
  },
  async redirects() {
    // 301 map from the previous static site, generated by
    // scripts/generate-redirects.mjs. Hand-written rules are preserved by the
    // generator, so add new ones there rather than editing the data file.
    return REDIRECTS;
  },
};

export default nextConfig;
