import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono, Playfair_Display, Inter } from "next/font/google";
import "./globals.css";
import FloatingActions from "@/components/layout/FloatingActions";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";

const GTM_ID = "GTM-TDRKCK4P";
const GA_ID = "G-VQXVM6ER4R";
const FB_PIXEL_ID = "609012521626024";

const productSchema = {
  "@context": "https://schema.org/",
  "@type": "Product",
  name: "Law College in Chennai, India | LL.B & LL.M Programs",
  image: "https://vmls.edu.in/",
  description:
    "Apply Today! Vinayaka Mission's Law School, the best Law College in Chennai, India, offers LL.B. and LL.M. programs in Corporate & Financial Laws and Commercial Dispute Resolution.",
  brand: { "@type": "Brand", name: "Vinayaka Mission's Law School (VMLS)" },
  aggregateRating: {
    "@type": "AggregateRating",
    ratingValue: 4.9,
    bestRating: 5,
    worstRating: 1,
    ratingCount: 2567,
  },
};

const localBusinessSchema = {
  "@context": "https://schema.org",
  "@id": "https://vmls.edu.in/",
  "@type": "LocalBusiness",
  name: "Vinayaka Mission's Law School (VMLS) | Law Colleges in Chennai, Tamilnadu",
  url: "https://vmls.edu.in/",
  telephone: "+91 73582 01234",
  image:
    "https://lh3.googleusercontent.com/5VhXtqPQlWuXVBUfftm_Lr_qKjouFJxFIfA036ICiNZ-_1Oei_go9MR_HnCm4GQuR8xuqgjW9blZqBoP=s0",
  hasMap: "https://maps.google.com/maps?cid=7328439174727332542",
  description:
    "Vinayaka Mission's Law School (VMLS), a top law college in Chennai, Tamilnadu offers world-class legal education...",
  address: {
    "@type": "PostalAddress",
    addressCountry: "IN",
    addressLocality: "Paiyanur",
    addressRegion: "IN",
    postalCode: "603104",
    streetAddress: "Vinayaka Nagar, Rajiv Gandhi Salai",
  },
  aggregateRating: {
    "@type": "AggregateRating",
    bestRating: "5",
    ratingCount: "64",
    ratingValue: "4.5",
  },
  openingHoursSpecification: [
    "MONDAY",
    "TUESDAY",
    "WEDNESDAY",
    "THURSDAY",
    "FRIDAY",
    "SATURDAY",
  ].map((d) => ({
    "@type": "OpeningHoursSpecification",
    dayOfWeek: d,
    opens: "09:00:00",
    closes: "18:00:00",
  })),
  makesOffer: [{ "@type": "Offer", name: "Law College" }],
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} ${inter.variable} h-full antialiased`}
    >
      <head>
        <Script
          id="gtm-init"
          strategy="afterInteractive"
        >{`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','${GTM_ID}');`}</Script>

        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`}
          strategy="afterInteractive"
        />
        <Script id="ga-init" strategy="afterInteractive">{`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', '${GA_ID}');
        `}</Script>

        <Script id="fb-pixel" strategy="afterInteractive">{`
          !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');
          fbq('init', '${FB_PIXEL_ID}');
          fbq('track', 'PageView');
        `}</Script>

        <Script
          id="ld-product"
          type="application/ld+json"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }}
        />
        <Script
          id="ld-localbusiness"
          type="application/ld+json"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusinessSchema) }}
        />
      </head>
      <body className={`${inter.variable} ${playfair.variable} antialiased`}>
        <noscript>
          <iframe
            src={`https://www.googletagmanager.com/ns.html?id=${GTM_ID}`}
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          />
        </noscript>
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src={`https://www.facebook.com/tr?id=${FB_PIXEL_ID}&ev=PageView&noscript=1`}
            alt=""
          />
        </noscript>

        <Header />
        <div className="animate-page-fade">{children}</div>
        <Footer />
        <FloatingActions />

        <Script id="npf-config" strategy="afterInteractive">
          {`
            var npf_d='https://admissions.vmls.edu.in';
            var npf_c='87feca6bc65be091ed018757c6c58029';
            var s=document.createElement("script");
            s.type="text/javascript";
            s.async=true;
            s.src="https://widgets.nopaperforms.com/em-widget.js";
            document.head.appendChild(s);
          `}
        </Script>
      </body>
    </html>
  );
}
