// AUTO-GENERATED by scripts/generate-blog-seo.mjs - do not edit by hand.
// Source of truth: src/app/blogs/[slug]/page.tsx (blogData).
export type BlogSeo = {
  slug: string;
  title: string;
  author: string;
  date: string;
  image: string;
  description: string;
};

export const BLOG_SEO: Record<string, BlogSeo> = {
  "cle-impact-on-healthcare-laws-and-patients-rights-in-india": {
    "slug": "cle-impact-on-healthcare-laws-and-patients-rights-in-india",
    "title": "The CLE Approach To Healthcare Laws & Patient Rights",
    "author": "Rudra Chandran L",
    "date": "July 03, 2025",
    "image": "/images/blogs/cle-in-healthcare.webp",
    "description": "In 2024, A couple approached the Delhi High Court for the purpose of retrieving their deceased son's cryopreserved sperm and using it for surrogacy. More…"
  },
  "global-perspective-clinical-legal-education": {
    "slug": "global-perspective-clinical-legal-education",
    "title": "Global Perspectives on Clinical Legal Education",
    "author": "Dr. Kannan Kunnathully",
    "date": "July 02, 2025",
    "image": "/images/blogs/global.webp",
    "description": "The fraternity of legal profession is noble in its true sense. To realise and enjoy this, a budding member should be well aware of the legal principles. In…"
  },
  "shaping-legal-futures-cle-and-constitutional-law": {
    "slug": "shaping-legal-futures-cle-and-constitutional-law",
    "title": "Shaping Legal Futures: CLE & Constitutional Law",
    "author": "Narayanan Chandrasekar",
    "date": "July 01, 2025",
    "image": "/images/blogs/shaping-legal.webp",
    "description": "Starting from King John’s Magna Carta, Eleanor Roosevelt’s role in the Universal Declaration of Human Rights, and B.R. Ambedkar’s contribution to the…"
  },
  "law-and-economics-in-clinical-legal-education-recasting-experiential-learning-in-the-5-year-llb-program": {
    "slug": "law-and-economics-in-clinical-legal-education-recasting-experiential-learning-in-the-5-year-llb-program",
    "title": "Law and Economics in Clinical Legal Education",
    "author": "Tathagat Sharma",
    "date": "June 30, 2025",
    "image": "/images/blogs/law-and-economics-in-clinical-legal-education.webp",
    "description": "Clinical Legal Education (CLE) has become a cornerstone of professional legal training in India, particularly through the 5-Year Integrated LLB Program…"
  },
  "fostering-legal-skills-and-advancing-social-justice-through-cle": {
    "slug": "fostering-legal-skills-and-advancing-social-justice-through-cle",
    "title": "How CLE Enhances Legal Skills & Social Justice",
    "author": "Kamala Priyadarshini",
    "date": "July 06, 2025",
    "image": "/images/blogs/how-cle-enhances-legal-skills-and-social-justice.webp",
    "description": "Clinical Legal Education (CLE) today plays a vital role in transforming legal education in India. It bridges the gap between theoretical knowledge and…"
  },
  "justice-at-the-grassroots-clinical-legal-education-and-family-law-practice-in-india": {
    "slug": "justice-at-the-grassroots-clinical-legal-education-and-family-law-practice-in-india",
    "title": "Justice at the Grassroots: CLE & Family Law",
    "author": "Abhinandita Biswas",
    "date": "July 05, 2025",
    "image": "/images/blogs/justice-at-glassdoors.webp",
    "description": "In India, family law is deeply personal and often emotional. Issues like marriage, divorce, and maintenance affect the most vulnerable—women and children—who…"
  },
  "decoding-competition-law-the-cle-approach": {
    "slug": "decoding-competition-law-the-cle-approach",
    "title": "Decoding Competition Law: The CLE Approach",
    "author": "Hartej Singh",
    "date": "July 04, 2025",
    "image": "/images/blogs/understanding-competition-law-via-cle.webp",
    "description": "Competition law is not just about markets or numbers—it is about power. Who has it, how do they use it, and what happens when it is used without limits? Most…"
  },
  "empowering-women-through-clinical-legal-education-in-india": {
    "slug": "empowering-women-through-clinical-legal-education-in-india",
    "title": "Empowering Women through Clinical Legal Education",
    "author": "Mike Ruban",
    "date": "June 30, 2025",
    "image": "/images/blogs/empowering-woman.webp",
    "description": "Patriarchy and casteism continue to impact women in rural and suburban Tamil Nadu, often normalizing domestic violence and dowry harassment. Accessing…"
  },
  "why-clinical-legal-education-and-adr-are-crucial-for-indian-justice": {
    "slug": "why-clinical-legal-education-and-adr-are-crucial-for-indian-justice",
    "title": "Why Clinical Legal Education and ADR Are Crucial",
    "author": "Shubham Shukla",
    "date": "June 29, 2025",
    "image": "/images/blogs/cle-and-adr.webp",
    "description": "The best way to learn law is by practicing it. Clinical Legal Education (CLE) takes students out of the classroom and into the real world, where they handle…"
  },
  "criminal-law-and-forensics-how-cle-shapes-legal-practice": {
    "slug": "criminal-law-and-forensics-how-cle-shapes-legal-practice",
    "title": "Criminal Law and Forensics: CLE in Action",
    "author": "Dr. Fowmina",
    "date": "June 29, 2025",
    "image": "/images/blogs/criminal-law-and-forensics.webp",
    "description": "In every murder case, there are two stories: the one heard in court and the one found at the crime scene. Justice is often found in the intersection of…"
  },
  "lack-of-clinical-legal-education-in-india": {
    "slug": "lack-of-clinical-legal-education-in-india",
    "title": "The CLE Gap in India: Impacts & Implications",
    "author": "Srinivas Raman",
    "date": "June 28, 2025",
    "image": "/images/blogs/20.webp",
    "description": "The concept of business and human rights has gained global popularity, yet it is rare to see law schools in India train students in clinical legal education…"
  },
  "llm-in-criminal-law-and-practice": {
    "slug": "llm-in-criminal-law-and-practice",
    "title": "LLM in Criminal Law and Practice",
    "author": "VMLS",
    "date": "June 27, 2025",
    "image": "/images/blogs/35.webp",
    "description": "Law as a career is growing rapidly in India; as a result, students are eager to learn more about the various specialisations in this domain. Not only…"
  },
  "llm-in-artificial-intelligence-emerging-technologies-and-intellectual-property-rights": {
    "slug": "llm-in-artificial-intelligence-emerging-technologies-and-intellectual-property-rights",
    "title": "LLM in AI, Tech and Intellectual Property",
    "author": "VMLS",
    "date": "June 27, 2025",
    "image": "/images/blogs/34.webp",
    "description": "Law is seen as a great career opportunity among students in India. It is one of the most sought-after courses in the current times, as it enables students to…"
  },
  "what-is-llm-master-of-law-degree": {
    "slug": "what-is-llm-master-of-law-degree",
    "title": "What is an LLM Master of Law Degree?",
    "author": "VMLS",
    "date": "June 26, 2025",
    "image": "/images/blogs/ll.m-full-form.webp",
    "description": "Law is emerging as a great career in India, and the need for highly qualified lawyers is rising significantly. For this purpose, after completing one’s LLB…"
  },
  "bringing-indian-contracts-ii-to-life-clinical-legal-education-vmls": {
    "slug": "bringing-indian-contracts-ii-to-life-clinical-legal-education-vmls",
    "title": "Bringing Indian Contracts II to Life Through CLE",
    "author": "Abhinaya Ramesh",
    "date": "June 25, 2025",
    "image": "/images/blogs/19.webp",
    "description": "Clinical Legal Education (CLE) for Indian Contract Law II is significant because it offers a practical, hands-on approach to legal learning, which is very…"
  },
  "empowering-future-advocates-clinical-legal-education-initiative-at-vmls": {
    "slug": "empowering-future-advocates-clinical-legal-education-initiative-at-vmls",
    "title": "Empowering Future Advocates: The CLE Initiative",
    "author": "Najeed Naved Siddiqui",
    "date": "June 10, 2025",
    "image": "/images/blogs/21.webp",
    "description": "Today’s legal teaching is emerging everywhere outside of the classroom. It is now more valuable to prepare students to engage with the real world, rather…"
  },
  "black-carbon-and-the-law-response": {
    "slug": "black-carbon-and-the-law-response",
    "title": "Black Carbon and the Law's Response",
    "author": "VMLS",
    "date": "June 20, 2025",
    "image": "/images/blogs/carbon.webp",
    "description": "Climate change stands as the central global problem of our time, directly affecting economic systems, community structures and natural ecosystems. While…"
  },
  "clinical-legal-education-in-india": {
    "slug": "clinical-legal-education-in-india",
    "title": "Clinical Legal Education in India",
    "author": "Ashwani Kumar Singh",
    "date": "June 20, 2025",
    "image": "/images/blogs/12.webp",
    "description": "Clinical Legal Education (CLE) in India has emerged as a significant component of the legal education system, bridging the gap between theoretical knowledge…"
  },
  "how-clinical-legal-education-enhances-management-disciplines": {
    "slug": "how-clinical-legal-education-enhances-management-disciplines",
    "title": "How Clinical Legal Education Enhances Management Disciplines?",
    "author": "Dr. Shenbagavalli",
    "date": "June 10, 2025",
    "image": "/images/blogs/11.webp",
    "description": "In today’s increasingly complex business landscape, the intersection of law and management is more crucial than ever. Clinical legal education (CLE) proves…"
  },
  "important-component-of-clinical-legal-education": {
    "slug": "important-component-of-clinical-legal-education",
    "title": "Important Component Of Clinical Legal Education",
    "author": "Ananyo Mitra",
    "date": "June 09, 2025",
    "image": "/images/blogs/18.webp",
    "description": "The purpose of legal education is to create proficient individuals who can render the best legal service. Along with a robust foundation of substantive law…"
  },
  "future-human-rights-advocates-clinical-legal-education": {
    "slug": "future-human-rights-advocates-clinical-legal-education",
    "title": "Empowering Future Human Rights Advocates",
    "author": "Amrita Nambiar",
    "date": "June 06, 2025",
    "image": "/images/blogs/13.webp",
    "description": "Classrooms and casebooks are no longer the exclusive means for legal education in India. Evolution is necessary to meet the challenges of pressing human…"
  },
  "clinical-education-in-financial-frauds-white-collar-crimes": {
    "slug": "clinical-education-in-financial-frauds-white-collar-crimes",
    "title": "Clinical Education In Financial Frauds",
    "author": "Sowmiya Narayan",
    "date": "June 05, 2025",
    "image": "/images/blogs/14.webp",
    "description": "The area of financial and white-collar crimes is a niche field that is rapidly growing in both law firm practice and litigation. While students are often…"
  },
  "law-in-practice-civil-procedure-learning-in-chennai-through-clinical-legal-education": {
    "slug": "law-in-practice-civil-procedure-learning-in-chennai-through-clinical-legal-education",
    "title": "Transforming Civil Procedure Learning in Chennai",
    "author": "Saravanan R",
    "date": "June 02, 2025",
    "image": "/images/blogs/civil-procedure.webp",
    "description": "In a justice system criticized for being slow and intimidating, the Civil Procedure Code (CPC) can feel like a list of sections on paper. Clinical Legal…"
  },
  "need-for-environmental-law-clinics-in-india": {
    "slug": "need-for-environmental-law-clinics-in-india",
    "title": "Need for Environmental Law Clinics in India",
    "author": "Nabeela Siddiqui",
    "date": "June 02, 2025",
    "image": "/images/blogs/environmental.webp",
    "description": "Environmental law clinics have evolved as potent instruments for promoting justice and sustainability. In India, where ecological desecration and legal…"
  },
  "top-bilingual-law-schools-in-chennai": {
    "slug": "top-bilingual-law-schools-in-chennai",
    "title": "Top Bilingual Law Schools in Chennai",
    "author": "VMLS",
    "date": "May 27, 2025",
    "image": "/images/blogs/bilingual.webp",
    "description": "Chennai is known for its educational prowess, and Vinayaka Mission’s Law School (VMLS) stands out as a leader in bilingual legal education. As the profession…"
  },
  "beyond-the-classroom-clinical-legal-education-promise": {
    "slug": "beyond-the-classroom-clinical-legal-education-promise",
    "title": "Beyond the Classroom: Is CLE Fulfilling Its Promise?",
    "author": "Sinjini Sen",
    "date": "May 23, 2025",
    "image": "/images/blogs/beyond-class.webp",
    "description": "Clinical Legal Education (CLE) creates a learning environment that replicates the real world. In India, while theoretical law has been the focus for decades…"
  },
  "clinical-legal-education-justice-for-marginalized": {
    "slug": "clinical-legal-education-justice-for-marginalized",
    "title": "Clinical Legal Education: Justice for Marginalized",
    "author": "Edhaya Chandran",
    "date": "May 22, 2025",
    "image": "/images/blogs/marginalized.webp",
    "description": "In a country of 1.5 billion people, access to justice is a serious challenge. For marginalized communities, legal aid is the bridge to the justice delivery…"
  },
  "why-sharing-your-childs-exam-results-online-can-impact-their-future": {
    "slug": "why-sharing-your-childs-exam-results-online-can-impact-their-future",
    "title": "Why Sharing Your Child's Exam Results Online Can Impact Their Future",
    "author": "VMLS",
    "date": "May 17, 2025",
    "image": "/images/blogs/1.webp",
    "description": "Sharing your child’s academic success on social media may seem harmless, but it can lead to unintended legal and personal consequences. From digital footprin…"
  },
  "clinical-legal-education-and-evidence-law-training-in-india": {
    "slug": "clinical-legal-education-and-evidence-law-training-in-india",
    "title": "Theory and Practice: CLE and Evidence Law Training",
    "author": "Nishant Sheokand",
    "date": "May 17, 2025",
    "image": "/images/blogs/2.webp",
    "description": "\"It is one thing to know that the law and quite another to practice it.\" This remark by N.R. Madhava Menon definitely highlights the fundamental gap between…"
  },
  "why-clinical-legal-education-in-india-is-struggling": {
    "slug": "why-clinical-legal-education-in-india-is-struggling",
    "title": "Why Clinical Legal Education in India Is Struggling?",
    "author": "VMLS",
    "date": "May 14, 2025",
    "image": "/images/blogs/clinical-legal.webp",
    "description": "Over the past few decades, legal education in India has come a long way. With the rise of global legal services and the increasing need for practical skills…"
  },
  "top-5-legal-careers-in-india-2025": {
    "slug": "top-5-legal-careers-in-india-2025",
    "title": "Top 5 Legal Careers in India for 2025",
    "author": "VMLS",
    "date": "May 13, 2025",
    "image": "/images/blogs/top-5-legal-careers.webp",
    "description": "The legal profession in India is no longer confined to courtrooms and corporate boardrooms. As our society evolves digitally and globally, so does the demand…"
  },
  "how-deepseeks-ai-is-shaping-litigation-support": {
    "slug": "how-deepseeks-ai-is-shaping-litigation-support",
    "title": "How DeepSeek’s AI is Shaping Litigation Support",
    "author": "VMLS",
    "date": "May 02, 2025",
    "image": "/images/blogs/deepseek.webp",
    "description": "DeepSeek AI has democratized access to Artificial Intelligence in the legal sector. As a free-to-use reasoning engine, it presents a unique opportunity to…"
  },
  "what-is-financial-law": {
    "slug": "what-is-financial-law",
    "title": "What is Financial Law?",
    "author": "VMLS",
    "date": "January 30, 2025",
    "image": "/images/blogs/financial.webp",
    "description": "Financial law plays a pivotal role in shaping the stability and transparency of global markets. It is the guiding framework that ensures transactions—from…"
  },
  "what-is-corporate-law": {
    "slug": "what-is-corporate-law",
    "title": "What is Corporate Law?",
    "author": "VMLS",
    "date": "January 29, 2025",
    "image": "/images/blogs/corporate.webp",
    "description": "Corporate law is the backbone of the business world, governing how companies are formed, operated, and dissolved. It ensures ethical practices and creates…"
  },
  "indus-waters-treaty-suspension-lessons-for-law-students": {
    "slug": "indus-waters-treaty-suspension-lessons-for-law-students",
    "title": "Water Wars and International Law",
    "author": "VMLS",
    "date": "January 24, 2025",
    "image": "/images/blogs/indus-water.webp",
    "description": "India’s official suspension of the Indus Waters Treaty (IWT) in 2025 marks a significant legal and geopolitical development. For law students, this scenario…"
  },
  "llm-in-corporate-financial-laws": {
    "slug": "llm-in-corporate-financial-laws",
    "title": "LLM in Corporate & Financial Laws",
    "author": "VMLS",
    "date": "March 13, 2025",
    "image": "/images/blogs/32.webp",
    "description": "The demand for specialized legal professionals is on the rise. Pursuing an LLM in Corporate and Financial Laws is an excellent way to enhance expertise in…"
  },
  "llm-in-commercial-dispute-resolution": {
    "slug": "llm-in-commercial-dispute-resolution",
    "title": "LLM in Commercial Dispute Resolution",
    "author": "VMLS",
    "date": "March 12, 2025",
    "image": "/images/blogs/33.webp",
    "description": "Commercial Dispute Resolution has been in practice for decades, and mechanisms such as arbitration and negotiation are of much need as per the law. The rise…"
  },
  "ex-ante-regulation": {
    "slug": "ex-ante-regulation",
    "title": "Ex Ante Regulation",
    "author": "VMLS",
    "date": "February 4, 2025",
    "image": "/images/blogs/ex-ante.webp",
    "description": "In an era defined by rapid technological changes, traditional methods of governing markets often struggle to keep pace. Competition laws have conventionally…"
  },
  "merger-regulations-expansion-competition-developing-economies": {
    "slug": "merger-regulations-expansion-competition-developing-economies",
    "title": "Merger Regulations in Developing Economies",
    "author": "VMLS",
    "date": "February 03, 2025",
    "image": "/images/blogs/role-merger.webp",
    "description": "Emerging economies frequently undergo swift industrialisation and globalisation, drawing substantial foreign direct investment (FDI). While mergers and…"
  },
  "network-effects-competition-law-digital-markets": {
    "slug": "network-effects-competition-law-digital-markets",
    "title": "Network Effects in Competition Law",
    "author": "VMLS",
    "date": "January 31, 2025",
    "image": "/images/blogs/network-effect.webp",
    "description": "Network effects arise when the value of a service increases as more individuals use it. In India’s dynamic digital landscape—covering social media, e-commerc…"
  },
  "mediation-for-operational-creditors": {
    "slug": "mediation-for-operational-creditors",
    "title": "Mediation for Operational Creditors",
    "author": "VMLS",
    "date": "January 30, 2025",
    "image": "/images/blogs/meditation.webp",
    "description": "The Insolvency and Bankruptcy Board of India (IBBI) has put forward an innovative plan aimed at streamlining the resolution process for operational creditors…"
  },
  "sebi-tightens-rules-for-futures-options-trading": {
    "slug": "sebi-tightens-rules-for-futures-options-trading",
    "title": "SEBI Tightens Rules for Futures and Options Trading",
    "author": "Shubham Shukla",
    "date": "January 27, 2025",
    "image": "/images/blogs/sebi.webp",
    "description": "In a significant move to safeguard investors and maintain market stability, the Securities and Exchange Board of India (SEBI) has introduced substantial…"
  },
  "climate-finance-development-in-india-cop29": {
    "slug": "climate-finance-development-in-india-cop29",
    "title": "Climate Finance Development in India",
    "author": "Shubham Shukla",
    "date": "January 24, 2025",
    "image": "/images/blogs/cop29.webp",
    "description": "As global environmental challenges intensify, the importance of climate finance has reached a pivotal point. During COP29, the international community…"
  },
  "one-year-llm-programme-vmls": {
    "slug": "one-year-llm-programme-vmls",
    "title": "One Year LLM Programme at VMLS",
    "author": "VMLS",
    "date": "January 21, 2025",
    "image": "/images/blogs/1-year.webp",
    "description": "Law is emerging as a great subject in India, and students are finding great career opportunities in this field. Having a degree in law from a top law college…"
  },
  "vinayaka-missions-law-admission-test-VLAT": {
    "slug": "vinayaka-missions-law-admission-test-VLAT",
    "title": "Vinayaka Mission's Law Admission Test (VLAT): A Complete Guide",
    "author": "VMLS",
    "date": "December 30, 2024",
    "image": "/images/blogs/VLAT.png",
    "description": "Vinayaka Mission’s Law School (VMLS) is recognised as one of India’s leading institutions for legal education. To gain admission into any of VMLS’s law…"
  },
  "5-year-llb-programme": {
    "slug": "5-year-llb-programme",
    "title": "5 Years LLB Programme at VMLS: Courses, Eligibility, Admission & Careers",
    "author": "VMLS",
    "date": "January 08, 2025",
    "image": "/images/blogs/5-Year.webp",
    "description": "Several students across India are choosing law as a career due to the various benefits it offers. It is a very promising field as it enables students to work…"
  },
  "3-year-llb-programme": {
    "slug": "3-year-llb-programme",
    "title": "3-Year LLB Programme at VMLS: Eligibility, Admission Criteria, Subjects, and Career Scope",
    "author": "VMLS",
    "date": "January 07, 2025",
    "image": "/images/blogs/3-Year.webp",
    "description": "The 3-Year LLB (Bachelor of Legislative Law) programme is designed for students who wish to pursue law after completing their graduation in any discipline…"
  },
  "best-law-courses-after-12th": {
    "slug": "best-law-courses-after-12th",
    "title": "Best Law Courses after 12th in India",
    "author": "VMLS",
    "date": "December 15, 2024",
    "image": "/images/blogs/best-law-courses-after-12th.webp",
    "description": "Choosing a career in law after the 12th standard is an increasingly popular and rewarding choice. Students can opt for 5-year integrated programmes, diploma…"
  },
  "clat-exam-importance-eligibility-criteria-syllabus": {
    "slug": "clat-exam-importance-eligibility-criteria-syllabus",
    "title": "CLAT Exam Guide: Importance, Eligibility, Syllabus & Preparation Tips",
    "author": "VMLS",
    "date": "December 10, 2024",
    "image": "/images/blogs/clat-exam.webp",
    "description": "CLAT (Common Law Entrance Test) is the most prestigious national-level entrance exam for law aspirants in India. It is the primary gateway to 24 National Law…"
  },
  "llb-degree-your-gateway-to-a-legal-career": {
    "slug": "llb-degree-your-gateway-to-a-legal-career",
    "title": "What is an LLB Degree? Significance, Eligibility, Subjects & Careers",
    "author": "VMLS",
    "date": "December 05, 2024",
    "image": "/images/blogs/llb-degree.webp",
    "description": "LLB stands for Bachelor of Legislative Law (Legum Baccalaureus). It is the foundational undergraduate degree for anyone aspiring to become a lawyer or a…"
  },
  "explore-diverse-career-opportunities-in-law-in-india-roles-necessary-skills-and-top-employers": {
    "slug": "explore-diverse-career-opportunities-in-law-in-india-roles-necessary-skills-and-top-employers",
    "title": "Career Opportunities in Law: Roles, Skills, Employers & Scope",
    "author": "VMLS",
    "date": "December 01, 2024",
    "image": "/images/blogs/llb.webp",
    "description": "Law is one of the most prestigious and sought-after careers in India. Beyond the courtroom, legal professionals are now essential in every sector—from…"
  },
  "types-of-law-courses-in-india": {
    "slug": "types-of-law-courses-in-india",
    "title": "Core Subjects in Law Courses: A Guide for Aspiring Legal Professionals",
    "author": "VMLS",
    "date": "November 25, 2024",
    "image": "/images/blogs/subject-in-law-course.webp",
    "description": "Whether you choose a 3-year LLB or a 5-year integrated programme, understanding the core subjects is essential to choosing your specialization and preparing…"
  },
  "best-law-colleges-in-india-how-to-choose-the-right-one": {
    "slug": "best-law-colleges-in-india-how-to-choose-the-right-one",
    "title": "Best Law Colleges in India: How to Choose the Right One",
    "author": "VMLS",
    "date": "December 23, 2024",
    "image": "/images/blogs/best-law-colleges-india.webp",
    "description": "Choosing the right law college is a defining moment for any legal aspirant. With India hosting hundreds of law institutions, from the prestigious National…"
  }
};

export const BLOG_SLUGS = Object.keys(BLOG_SEO);
