// AUTO-GENERATED by scripts/generate-og-image-sizes.mjs - do not edit.
// Real pixel dimensions of every image used as an og:image.
export const OG_IMAGE_SIZES: Record<string, [number, number]> = {
  "/images/AI/National Seminar on AI_01_webp.webp": [
    1280,
    720
  ],
  "/images/CAJ-img.webp": [
    1920,
    1080
  ],
  "/images/Frame89.webp": [
    1016,
    431
  ],
  "/images/atrium1.webp": [
    380,
    381
  ],
  "/images/blogs/1-year.webp": [
    1200,
    628
  ],
  "/images/blogs/1.webp": [
    1200,
    628
  ],
  "/images/blogs/11.webp": [
    1200,
    628
  ],
  "/images/blogs/12.webp": [
    1200,
    628
  ],
  "/images/blogs/13.webp": [
    1200,
    628
  ],
  "/images/blogs/14.webp": [
    1200,
    628
  ],
  "/images/blogs/18.webp": [
    1200,
    628
  ],
  "/images/blogs/19.webp": [
    1200,
    628
  ],
  "/images/blogs/2.webp": [
    1200,
    628
  ],
  "/images/blogs/20.webp": [
    1200,
    628
  ],
  "/images/blogs/21.webp": [
    1200,
    628
  ],
  "/images/blogs/3-Year.webp": [
    1200,
    628
  ],
  "/images/blogs/32.webp": [
    1200,
    628
  ],
  "/images/blogs/33.webp": [
    1200,
    628
  ],
  "/images/blogs/34.webp": [
    1200,
    628
  ],
  "/images/blogs/35.webp": [
    1500,
    784
  ],
  "/images/blogs/5-Year.webp": [
    1200,
    628
  ],
  "/images/blogs/VLAT.png": [
    848,
    444
  ],
  "/images/blogs/best-law-colleges-india.webp": [
    1200,
    628
  ],
  "/images/blogs/best-law-courses-after-12th.webp": [
    602,
    315
  ],
  "/images/blogs/beyond-class.webp": [
    3750,
    1962
  ],
  "/images/blogs/bilingual.webp": [
    1200,
    628
  ],
  "/images/blogs/carbon.webp": [
    1200,
    628
  ],
  "/images/blogs/civil-procedure.webp": [
    1200,
    628
  ],
  "/images/blogs/clat-exam.webp": [
    602,
    315
  ],
  "/images/blogs/cle-and-adr.webp": [
    1200,
    628
  ],
  "/images/blogs/cle-in-healthcare.webp": [
    1200,
    628
  ],
  "/images/blogs/clinical-legal.webp": [
    800,
    419
  ],
  "/images/blogs/cop29.webp": [
    1200,
    628
  ],
  "/images/blogs/corporate.webp": [
    1200,
    628
  ],
  "/images/blogs/criminal-law-and-forensics.webp": [
    1200,
    628
  ],
  "/images/blogs/deepseek.webp": [
    1200,
    628
  ],
  "/images/blogs/empowering-woman.webp": [
    1200,
    628
  ],
  "/images/blogs/environmental.webp": [
    1200,
    628
  ],
  "/images/blogs/ex-ante.webp": [
    1200,
    628
  ],
  "/images/blogs/financial.webp": [
    1200,
    628
  ],
  "/images/blogs/global.webp": [
    1200,
    628
  ],
  "/images/blogs/how-cle-enhances-legal-skills-and-social-justice.webp": [
    1200,
    628
  ],
  "/images/blogs/indus-water.webp": [
    1200,
    628
  ],
  "/images/blogs/justice-at-glassdoors.webp": [
    1200,
    628
  ],
  "/images/blogs/law-and-economics-in-clinical-legal-education.webp": [
    1200,
    628
  ],
  "/images/blogs/ll.m-full-form.webp": [
    1200,
    628
  ],
  "/images/blogs/llb-degree.webp": [
    602,
    315
  ],
  "/images/blogs/llb.webp": [
    1200,
    628
  ],
  "/images/blogs/marginalized.webp": [
    1500,
    785
  ],
  "/images/blogs/meditation.webp": [
    1200,
    628
  ],
  "/images/blogs/network-effect.webp": [
    1200,
    628
  ],
  "/images/blogs/role-merger.webp": [
    1200,
    628
  ],
  "/images/blogs/sebi.webp": [
    1200,
    628
  ],
  "/images/blogs/shaping-legal.webp": [
    1200,
    628
  ],
  "/images/blogs/subject-in-law-course.webp": [
    602,
    315
  ],
  "/images/blogs/top-5-legal-careers.webp": [
    1200,
    628
  ],
  "/images/blogs/understanding-competition-law-via-cle.webp": [
    1200,
    628
  ],
  "/images/bod/advisor-hero-bg.png": [
    1024,
    1024
  ],
  "/images/bod/mentor-hero-bg.png": [
    1024,
    1024
  ],
  "/images/career/hero.png": [
    1024,
    1024
  ],
  "/images/class1.webp": [
    380,
    381
  ],
  "/images/collab/Frame-53245.webp": [
    822,
    505
  ],
  "/images/collab/img5.webp": [
    1920,
    728
  ],
  "/images/cpil/guest-lecture.webp": [
    1600,
    900
  ],
  "/images/cpil/il0.webp": [
    1920,
    728
  ],
  "/images/cpil/rivers.webp": [
    1600,
    900
  ],
  "/images/faculty/02.webp": [
    500,
    500
  ],
  "/images/faculty/03.webp": [
    581,
    581
  ],
  "/images/faculty/05.webp": [
    581,
    581
  ],
  "/images/faculty/09.webp": [
    581,
    581
  ],
  "/images/faculty/12.webp": [
    581,
    581
  ],
  "/images/faculty/14.webp": [
    581,
    581
  ],
  "/images/faculty/19.webp": [
    581,
    581
  ],
  "/images/faculty/21.webp": [
    500,
    500
  ],
  "/images/faculty/38.jpeg": [
    853,
    857
  ],
  "/images/faculty/39.webp": [
    550,
    550
  ],
  "/images/faculty/40.webp": [
    550,
    550
  ],
  "/images/faculty/41.webp": [
    550,
    550
  ],
  "/images/faculty/42.webp": [
    637,
    637
  ],
  "/images/faculty/43.webp": [
    734,
    734
  ],
  "/images/faculty/44.webp": [
    550,
    550
  ],
  "/images/faculty/45.jpeg": [
    413,
    531
  ],
  "/images/faculty/46.webp": [
    3273,
    3273
  ],
  "/images/faculty/47.webp": [
    1024,
    1024
  ],
  "/images/faculty/48.webp": [
    800,
    800
  ],
  "/images/faculty/49.webp": [
    500,
    500
  ],
  "/images/faculty/Aamir.jpeg": [
    3996,
    4985
  ],
  "/images/faculty/Abhinandita.webp": [
    333,
    333
  ],
  "/images/faculty/Abraham.jpeg": [
    1022,
    1280
  ],
  "/images/faculty/Akshara Nair.jpeg": [
    413,
    531
  ],
  "/images/faculty/Anuttama.jpeg": [
    1396,
    1516
  ],
  "/images/faculty/Dr. Jacob Joseph_Photo.jpeg": [
    2182,
    1905
  ],
  "/images/faculty/Dr. Yazhini A.jpeg": [
    537,
    555
  ],
  "/images/faculty/Dr_Shabin.jpeg": [
    747,
    1280
  ],
  "/images/faculty/Kush Tanvani.webp": [
    531,
    673
  ],
  "/images/faculty/R. Sneha.jpeg": [
    676,
    861
  ],
  "/images/faculty/Stalin Harikaran N.jpeg": [
    1200,
    1467
  ],
  "/images/faculty/aarthy.webp": [
    550,
    550
  ],
  "/images/faculty/alisha.jpeg": [
    757,
    840
  ],
  "/images/faculty/arun.webp": [
    378,
    378
  ],
  "/images/faculty/avni.jpeg": [
    1066,
    977
  ],
  "/images/faculty/gaurav.webp": [
    500,
    500
  ],
  "/images/faculty/hartej.webp": [
    500,
    500
  ],
  "/images/faculty/kamala.webp": [
    500,
    500
  ],
  "/images/faculty/kiran.webp": [
    550,
    550
  ],
  "/images/faculty/luke.webp": [
    500,
    500
  ],
  "/images/faculty/muthuvel.webp": [
    550,
    550
  ],
  "/images/faculty/sachin.jpeg": [
    320,
    289
  ],
  "/images/faculty/victor.jpeg": [
    220,
    221
  ],
  "/images/global/in8.webp": [
    578,
    320
  ],
  "/images/global/inter-tamil-law.webp": [
    1400,
    788
  ],
  "/images/global/tamil-moot.webp": [
    1600,
    900
  ],
  "/images/global/tl1.webp": [
    1916,
    728
  ],
  "/images/home-about.webp": [
    800,
    649
  ],
  "/images/home-faculty.webp": [
    1000,
    667
  ],
  "/images/hostel3.webp": [
    380,
    379
  ],
  "/images/il1.webp": [
    1603,
    556
  ],
  "/images/iqac/iqac-1.webp": [
    1200,
    800
  ],
  "/images/iqac/report-on-workshop2.webp": [
    1600,
    1199
  ],
  "/images/justice/Frame53138.webp": [
    768,
    396
  ],
  "/images/justice/ai-center-of-justice.webp": [
    1600,
    900
  ],
  "/images/justice/e-filling.webp": [
    1600,
    900
  ],
  "/images/justice/flip-case.webp": [
    1600,
    900
  ],
  "/images/library-header-img.webp": [
    1824,
    911
  ],
  "/images/library-rules-header.png": [
    1024,
    1024
  ],
  "/images/library/library5.webp": [
    1280,
    853
  ],
  "/images/llb/2.webp": [
    716,
    548
  ],
  "/images/llm/1.webp": [
    1600,
    1065
  ],
  "/images/llm/admission-header.webp": [
    1920,
    824
  ],
  "/images/maritime/distinguish-guest.webp": [
    1600,
    900
  ],
  "/images/maritime/maritime.webp": [
    1599,
    899
  ],
  "/images/maritime/ml0.webp": [
    1920,
    728
  ],
  "/images/maritime/special-lecture-maritime.webp": [
    1600,
    900
  ],
  "/images/mb1.webp": [
    380,
    381
  ],
  "/images/mcourt1.webp": [
    380,
    381
  ],
  "/images/mentor.webp": [
    1200,
    1206
  ],
  "/images/news/3rd.webp": [
    1200,
    600
  ],
  "/images/news/Gender Equality_02.webp": [
    1600,
    1200
  ],
  "/images/news/Lecture-ethics.webp": [
    768,
    576
  ],
  "/images/news/student1.webp": [
    1333,
    861
  ],
  "/images/schlorship/01.webp": [
    752,
    520
  ],
  "/images/shall1.webp": [
    380,
    381
  ],
  "/images/studentaff/1.webp": [
    1200,
    600
  ],
  "/images/studentaff/moot.webp": [
    324,
    394
  ],
  "/images/studentaff/sports.webp": [
    324,
    394
  ],
  "/images/studentaff/thumbnail.webp": [
    330,
    180
  ],
  "/images/vmls/frame-1@3x.webp": [
    1920,
    1080
  ],
  "/images/vmls/vmls-arch.png": [
    1024,
    1024
  ],
  "/images/vmrf/Frame-53135.webp": [
    263,
    246
  ],
  "/images/vmrf/Frame-53136.webp": [
    263,
    246
  ],
  "/images/vmrf/vmrf-header.webp": [
    1920,
    864
  ]
};
