// AUTO-GENERATED by scripts/generate-og-image-sizes.mjs - do not edit.
// Real pixel dimensions of every image used as an og:image.
export const OG_IMAGE_SIZES: Record<string, [number, number]> = {
  "/images/AI/national-seminar-on-ai-01.webp": [
    1280,
    720
  ],
  "/images/CAJ-img.webp": [
    1600,
    900
  ],
  "/images/Frame89.webp": [
    1016,
    431
  ],
  "/images/atrium1.webp": [
    380,
    381
  ],
  "/images/blogs/3-year-llb-admission-chennai-tamilnadu__3yearllbadmissioninchennai.png": [
    847,
    444
  ],
  "/images/blogs/3-year-llb-programme-india-2026__3-year-llb-programme-in-scope-2026.png": [
    848,
    444
  ],
  "/images/blogs/3-year-llb-programme__3-year.webp": [
    1200,
    628
  ],
  "/images/blogs/3-year-llb-vs-5-year-llb-comparison__3yearllbvs5yearllb.png": [
    847,
    444
  ],
  "/images/blogs/5-year-ba-llb-hons__wp.png": [
    848,
    444
  ],
  "/images/blogs/5-year-bba-llb-hons__wp.png": [
    848,
    444
  ],
  "/images/blogs/5-year-bcom-llb-hons__wp.png": [
    848,
    444
  ],
  "/images/blogs/5-year-integrated-llb-programme-india-2026__5-year-integrated-llb-programme-india-2026.png": [
    848,
    444
  ],
  "/images/blogs/5-year-llb-programme__5-year.webp": [
    1200,
    628
  ],
  "/images/blogs/aibe-all-india-bar-exam-guide__aibe-guide-eligibility-pattern-prep.png": [
    847,
    444
  ],
  "/images/blogs/ba-llb-admission-2026-eligibility-application-process-fees-career-opportunities__wp.png": [
    848,
    444
  ],
  "/images/blogs/ba-llb-course-in-india-eligibility-fees-duration-best-law-colleges__wp.png": [
    848,
    444
  ],
  "/images/blogs/ba-llb-hons-programme-2026__ba-llb-hons-2026.png": [
    848,
    444
  ],
  "/images/blogs/ba-llb-vs-bba-llb-vs-bcom-llb-comparison__ba-llb-vs-bba-llb-vs-bcom-llb.png": [
    847,
    444
  ],
  "/images/blogs/bachelors-degree-in-law__wp.png": [
    1200,
    628
  ],
  "/images/blogs/bba-llb-colleges-in-india-2026__bba-llb-colleges-in-india-2026.png": [
    848,
    444
  ],
  "/images/blogs/bcom-llb-colleges-india-2026-27__bcom-llb-colleges-in-india-2026-27.png": [
    848,
    444
  ],
  "/images/blogs/best-law-colleges-in-india-2026__best-law-colleges-in-india-2026.png": [
    848,
    444
  ],
  "/images/blogs/best-law-courses-after-12th__best-law-courses-after-12th.webp": [
    602,
    315
  ],
  "/images/blogs/best-time-to-apply-for-llb-admission-in-india__wp.png": [
    848,
    444
  ],
  "/images/blogs/beyond-the-classroom-clinical-legal-education-promise__beyond-class.webp": [
    1600,
    837
  ],
  "/images/blogs/bilingual-law-school-chennai-2026__bilingual-law-school-in-chennai.png": [
    848,
    444
  ],
  "/images/blogs/black-carbon-and-the-law-response__carbon.webp": [
    1200,
    628
  ],
  "/images/blogs/bringing-indian-contracts-ii-to-life-clinical-legal-education-vmls__19.webp": [
    1200,
    628
  ],
  "/images/blogs/career-after-llb-litigation-vs-corporate-vs-judiciary__career-after-llb.png": [
    847,
    444
  ],
  "/images/blogs/clat-2026-exam-dates-eligibility-syllabus-and-admission__clat-26.webp": [
    1200,
    628
  ],
  "/images/blogs/clat-2027-exam-dates-eligibility-syllabus-and-admission__clat-2027.png": [
    847,
    444
  ],
  "/images/blogs/clat-exam-importance-eligibility-criteria-syllabus__clat-exam.webp": [
    602,
    315
  ],
  "/images/blogs/cle-impact-on-healthcare-laws-and-patients-rights-in-india__cle-in-healthcare.webp": [
    1200,
    628
  ],
  "/images/blogs/cle-in-healthcare.webp": [
    1200,
    628
  ],
  "/images/blogs/climate-finance-development-in-india-cop29__cop29.webp": [
    1200,
    628
  ],
  "/images/blogs/clinical-education-in-financial-frauds-white-collar-crimes__13.webp": [
    1200,
    628
  ],
  "/images/blogs/clinical-legal-education-and-evidence-law-training-in-india__2.webp": [
    1200,
    628
  ],
  "/images/blogs/clinical-legal-education-in-india__21.webp": [
    1200,
    628
  ],
  "/images/blogs/clinical-legal-education-justice-for-marginalized__marginalized.webp": [
    1500,
    785
  ],
  "/images/blogs/common-mistakes-students-make-during-the-llb-admission-process__wp.png": [
    848,
    444
  ],
  "/images/blogs/corporate-law-courses-in-india-degrees-eligibility-salary__corporate-law-courses-in-india-degrees-eligibility-salary.png": [
    847,
    444
  ],
  "/images/blogs/criminal-law-and-forensics-how-cle-shapes-legal-practice__criminal-law-and-forensics.webp": [
    1200,
    628
  ],
  "/images/blogs/criminal-law-in-chennai-curriculum-degrees-careers__criminal-law-in-chennai-curriculum-degrees-careers.png": [
    847,
    444
  ],
  "/images/blogs/decoding-competition-law-the-cle-approach__understanding-competition-law-via-cle.webp": [
    1200,
    628
  ],
  "/images/blogs/empowering-future-advocates-clinical-legal-education-initiative-at-vmls__12.webp": [
    1200,
    628
  ],
  "/images/blogs/empowering-migrant-labourers-in-chennai-through-clinical-legal-education-and-access-to-justice__wp.png": [
    1200,
    628
  ],
  "/images/blogs/empowering-women-through-clinical-legal-education-in-india__empowering-woman.webp": [
    1200,
    628
  ],
  "/images/blogs/ex-ante-regulation__ex-ante.webp": [
    1200,
    628
  ],
  "/images/blogs/explore-diverse-career-opportunities-in-law-in-india-roles-necessary-skills-and-top-employers__llb.webp": [
    1200,
    628
  ],
  "/images/blogs/fostering-legal-skills-and-advancing-social-justice-through-cle__how-cle-enhances-legal-skills-and-social-justice.webp": [
    1200,
    628
  ],
  "/images/blogs/from-silence-to-recognition-why-recognising-menstrual-dignity-as-a-constitutional-right-was-long-overdue__wp.png": [
    848,
    444
  ],
  "/images/blogs/full-time-phd-in-law-and-interdisciplinary-studies__fix.webp": [
    1200,
    628
  ],
  "/images/blogs/future-human-rights-advocates-clinical-legal-education__14.webp": [
    1200,
    628
  ],
  "/images/blogs/global-exposure-indian-law-schools-mentorship__Global Exposure in Indian Law Schools_ Why It Matters.png": [
    847,
    444
  ],
  "/images/blogs/global-perspective-clinical-legal-education__global.webp": [
    1200,
    628
  ],
  "/images/blogs/how-clinical-legal-education-enhances-management-disciplines__11.webp": [
    1200,
    628
  ],
  "/images/blogs/how-deepseeks-ai-is-shaping-litigation-support__deepseek.webp": [
    1200,
    628
  ],
  "/images/blogs/how-to-become-a-judge-in-india-after-llb__how-to-become-a-judge-in-india-after-llb.png": [
    847,
    444
  ],
  "/images/blogs/how-to-choose-the-right-law-university-india__how-to-choose-the-right-law-university-in-india.png": [
    848,
    444
  ],
  "/images/blogs/how-to-prepare-for-vlat-study-plan__how-to-prepare-for-vlat.png": [
    847,
    444
  ],
  "/images/blogs/important-component-of-clinical-legal-education__18.webp": [
    1200,
    628
  ],
  "/images/blogs/india-anti-paper-leak-law-2026-explained__india-anti-paper-leak-law-2026-explained.png": [
    847,
    444
  ],
  "/images/blogs/indus-waters-treaty-suspension-lessons-for-law-students__indus-water.webp": [
    1200,
    628
  ],
  "/images/blogs/justice-at-the-grassroots-clinical-legal-education-and-family-law-practice-in-india__justice-at-glassdoors.webp": [
    1200,
    628
  ],
  "/images/blogs/lack-of-clinical-legal-education-in-india__the-cle-gap.webp": [
    1200,
    628
  ],
  "/images/blogs/law-and-economics-in-clinical-legal-education-recasting-experiential-learning-in-the-5-year-llb-program__law-and-economics-in-clinical-legal-education.webp": [
    1200,
    628
  ],
  "/images/blogs/law-colleges-in-chennai-2026-27__wp.png": [
    848,
    444
  ],
  "/images/blogs/law-courses-after-graduation-2026__law-courses-after-graduation-2026-new-one.png": [
    848,
    444
  ],
  "/images/blogs/law-courses-after-graduation-build-your-legal-career__wp.png": [
    848,
    444
  ],
  "/images/blogs/law-entrance-exam-vlat__wp.png": [
    848,
    444
  ],
  "/images/blogs/law-entrance-exams-clat-vs-vlat-comparison__law-entrance-exams-in-india.png": [
    847,
    444
  ],
  "/images/blogs/law-entrance-exams-in-india-2026-complete-guide__wp.png": [
    848,
    444
  ],
  "/images/blogs/law-in-practice-civil-procedure-learning-in-chennai-through-clinical-legal-education__civil-procedure.webp": [
    1200,
    628
  ],
  "/images/blogs/law-school-internships-year-by-year-guide__Law School Internships_ A Year-by-Year Guide.png": [
    847,
    444
  ],
  "/images/blogs/llb-admission-2026__llb-admission-2026-india.png": [
    848,
    444
  ],
  "/images/blogs/llb-admission-dates-process-checklist-2026-27__llb-fees-in-india-2026-27-admission-last-dates-1.png": [
    848,
    444
  ],
  "/images/blogs/llb-fees-in-india-2026-27__wp.png": [
    848,
    444
  ],
  "/images/blogs/llb-fees-in-india-complete-cost-breakdown__llb-fees-in-india.png": [
    847,
    444
  ],
  "/images/blogs/llb-fees-india-2026-27__llb-fees-in-india-2026-27.png": [
    848,
    444
  ],
  "/images/blogs/llb-hons-eligibility-admissions-syllabus__wp.png": [
    848,
    444
  ],
  "/images/blogs/llm-corporate-law-career-scope-2026-27__llm-in-corporate-law.png": [
    848,
    444
  ],
  "/images/blogs/llm-eligibility-requirements-for-master-of-laws-admission__wp.png": [
    848,
    444
  ],
  "/images/blogs/llm-entrance-exam-india-2026-27__wp.png": [
    848,
    444
  ],
  "/images/blogs/llm-in-artificial-intelligence-emerging-technologies-and-intellectual-property-rights__ll-m-ai-emerging-technologies-and-ipr.png": [
    848,
    444
  ],
  "/images/blogs/llm-in-commercial-dispute-resolution__ll-m-commercial-dispute-resolution.png": [
    848,
    444
  ],
  "/images/blogs/llm-in-corporate-financial-laws__ll-m-corporate-and-financial-laws.png": [
    848,
    444
  ],
  "/images/blogs/llm-in-criminal-law-and-practice__ll-m-criminal-law-and-practice-at-vmls.png": [
    848,
    444
  ],
  "/images/blogs/llm-programme-in-india-2026-27__wp.png": [
    848,
    444
  ],
  "/images/blogs/llm-specializations-guide-colleges-chennai__llm-in-india.png": [
    847,
    444
  ],
  "/images/blogs/mediation-for-operational-creditors__meditation.webp": [
    1200,
    628
  ],
  "/images/blogs/merger-regulations-expansion-competition-developing-economies__role-merger.webp": [
    1200,
    628
  ],
  "/images/blogs/moot-court-law-school-why-it-matters__Moot Court in Law School_ Why It Matters & How to Start.png": [
    847,
    444
  ],
  "/images/blogs/need-for-environmental-law-clinics-in-india__environmental.webp": [
    1200,
    628
  ],
  "/images/blogs/network-effects-competition-law-digital-markets__network-effect.webp": [
    1200,
    628
  ],
  "/images/blogs/one-year-llm-programme-vmls__1-year.webp": [
    1200,
    628
  ],
  "/images/blogs/part-time-phd-in-law-and-interdisciplinary-studies__fix.webp": [
    1200,
    628
  ],
  "/images/blogs/personality-rights-india-ai-deepfakes-law__personality-rights-india-ai-deepfakes-law.png": [
    847,
    444
  ],
  "/images/blogs/scholarships-for-law-students-in-india__scholarships-for-law-students-in-india-explained.png": [
    847,
    444
  ],
  "/images/blogs/sebi-tightens-rules-for-futures-options-trading__sebi.webp": [
    1200,
    628
  ],
  "/images/blogs/shaping-legal-futures-cle-and-constitutional-law__shaping-legal.webp": [
    1200,
    628
  ],
  "/images/blogs/step-by-step-guide-to-law-college-admission__wp.png": [
    848,
    444
  ],
  "/images/blogs/subjects-in-law-courses__subject-in-law-course.webp": [
    602,
    315
  ],
  "/images/blogs/supreme-court-handbook-judgments-gender-explained__supreme-court-handbook-judgments-gender-explained.png": [
    847,
    444
  ],
  "/images/blogs/the-best-law-college-for-bengaluru-students__wp.png": [
    848,
    444
  ],
  "/images/blogs/the-best-law-colleges-in-india__wp.webp": [
    1200,
    628
  ],
  "/images/blogs/third-party-litigation-funding-india-guide__third-party-litigation-funding-india-guide.png": [
    847,
    444
  ],
  "/images/blogs/three-year-llb-hons__wp.png": [
    848,
    444
  ],
  "/images/blogs/top-5-legal-careers-in-india-2025__top-5-legal-careers.webp": [
    1200,
    628
  ],
  "/images/blogs/top-bilingual-law-schools-in-chennai__bilingual.webp": [
    1200,
    628
  ],
  "/images/blogs/top-law-college-in-chennai-for-llb-llm-ph-d-admissions__wp.png": [
    1200,
    628
  ],
  "/images/blogs/top-law-colleges-in-tamil-nadu__wp.png": [
    848,
    444
  ],
  "/images/blogs/top-law-colleges-india__top-law-colleges-india.webp": [
    1200,
    628
  ],
  "/images/blogs/top-llm-colleges-in-india-2026-27__wp.png": [
    848,
    444
  ],
  "/images/blogs/tribunals-reforms-bill-2026-national-tribunals-commission__tribunals-reforms-bill-2026-national-tribunals-commission.png": [
    847,
    444
  ],
  "/images/blogs/types-of-law-courses-in-india__know-about-various-types.webp": [
    602,
    315
  ],
  "/images/blogs/vinayaka-missions-law-admission-test-VLAT__vlat.png": [
    848,
    444
  ],
  "/images/blogs/vinayaka-missions-law-school-signs-international-mou-with-university-of-san-diego-expanding-global-learning-opportunities__wp.jpeg": [
    848,
    444
  ],
  "/images/blogs/vmls-open-day-2025__fix.webp": [
    1200,
    628
  ],
  "/images/blogs/vmls-open-day-2026__vmls-open-day-2026.png": [
    1600,
    900
  ],
  "/images/blogs/vmrf-law-admission-test-vlat__vlat.png": [
    848,
    444
  ],
  "/images/blogs/vmrf-law-aptitude-test-vlat__vlat-3-0.webp": [
    1200,
    628
  ],
  "/images/blogs/what-does-bci-approval-mean-law-college__bci-approval-law-college.png": [
    847,
    444
  ],
  "/images/blogs/what-is-a-moot-court__wp.png": [
    1200,
    628
  ],
  "/images/blogs/what-is-corporate-law__corporate.webp": [
    1200,
    628
  ],
  "/images/blogs/what-is-financial-law__financial.webp": [
    1200,
    628
  ],
  "/images/blogs/what-is-llb-degree__what-is-an-llb-degree-everything-you-need-to-know-before-you-apply.png": [
    848,
    444
  ],
  "/images/blogs/what-is-llm-master-of-law-degree__ll-m-full-form.webp": [
    1200,
    628
  ],
  "/images/blogs/why-clinical-legal-education-and-adr-are-crucial-for-indian-justice__cle-and-adr.webp": [
    1200,
    628
  ],
  "/images/blogs/why-clinical-legal-education-in-india-is-struggling__clinical-legal.webp": [
    800,
    419
  ],
  "/images/blogs/why-distance-ll-b-degrees-are-not-approved-in-india__wp.png": [
    1200,
    628
  ],
  "/images/blogs/why-sharing-your-childs-exam-results-online-can-impact-their-future__1.webp": [
    1200,
    628
  ],
  "/images/bod/advisor-hero-bg.png": [
    1024,
    1024
  ],
  "/images/bod/mentor-hero-bg.png": [
    1024,
    1024
  ],
  "/images/career/hero.png": [
    1024,
    1024
  ],
  "/images/class1.webp": [
    380,
    381
  ],
  "/images/collab/Frame-53245.webp": [
    822,
    505
  ],
  "/images/conf/pg-head.webp": [
    1440,
    449
  ],
  "/images/cpil/guest-lecture.webp": [
    1600,
    900
  ],
  "/images/cpil/il0.webp": [
    1920,
    728
  ],
  "/images/cpil/rivers.webp": [
    1600,
    900
  ],
  "/images/faculty/live/19.webp": [
    289,
    289
  ],
  "/images/faculty/live/Anuttama.jpeg": [
    1396,
    1516
  ],
  "/images/faculty/live/DSC00387_8.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00390_5.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00395_30.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00401_27.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00413_13.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00440_2.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00449_4.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00473_3.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00475_18.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00504_11.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00524_7.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00537_28.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00539_22.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00550_36.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00566_34.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00570_23.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00584_16.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00586_10.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00612_21.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00618_33.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00631_32.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00643_12.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00647_35.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00648_14.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00665_20.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00674_9.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00677_31.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00688_26.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00695_24.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00704_25.webp": [
    1400,
    934
  ],
  "/images/faculty/live/DSC00754.webp": [
    1400,
    787
  ],
  "/images/faculty/live/DSC00804_017.webp": [
    1400,
    787
  ],
  "/images/faculty/live/hartej.webp": [
    500,
    500
  ],
  "/images/faculty/live/luke-live.webp": [
    500,
    500
  ],
  "/images/faculty/live/mike.webp": [
    1024,
    1024
  ],
  "/images/faculty/live/muthuvel.webp": [
    550,
    550
  ],
  "/images/faculty/live/najeed.webp": [
    550,
    550
  ],
  "/images/faculty/live/r-sneha-live.jpeg": [
    676,
    861
  ],
  "/images/foodc1.webp": [
    380,
    381
  ],
  "/images/global/in8.webp": [
    578,
    320
  ],
  "/images/global/inter-tamil-law.webp": [
    1400,
    788
  ],
  "/images/global/tamil-moot.webp": [
    1600,
    900
  ],
  "/images/global/tl1.webp": [
    1916,
    728
  ],
  "/images/home-about.webp": [
    800,
    649
  ],
  "/images/home-faculty.webp": [
    1000,
    667
  ],
  "/images/hostel3.webp": [
    380,
    379
  ],
  "/images/il1.webp": [
    1603,
    556
  ],
  "/images/iqac/iqac-1.webp": [
    1200,
    800
  ],
  "/images/iqac/report-on-workshop2.webp": [
    1600,
    1199
  ],
  "/images/justice/Frame53138.webp": [
    768,
    396
  ],
  "/images/justice/ai-center-of-justice.webp": [
    1600,
    900
  ],
  "/images/justice/e-filling.webp": [
    1600,
    900
  ],
  "/images/justice/flip-case.webp": [
    1600,
    900
  ],
  "/images/library-header-img.webp": [
    1600,
    799
  ],
  "/images/library-rules-header.png": [
    1024,
    1024
  ],
  "/images/library/library5.webp": [
    1280,
    853
  ],
  "/images/llb/2.webp": [
    716,
    548
  ],
  "/images/llm/1.webp": [
    1600,
    1065
  ],
  "/images/llm/admission-header.webp": [
    1920,
    824
  ],
  "/images/maritime/distinguish-guest.webp": [
    1600,
    900
  ],
  "/images/maritime/maritime.webp": [
    1599,
    899
  ],
  "/images/maritime/ml0.webp": [
    1920,
    728
  ],
  "/images/maritime/special-lecture-maritime.webp": [
    1600,
    900
  ],
  "/images/mb1.webp": [
    380,
    381
  ],
  "/images/mcourt1.webp": [
    380,
    381
  ],
  "/images/mentor.webp": [
    1200,
    1206
  ],
  "/images/news/3rd.webp": [
    1200,
    600
  ],
  "/images/news/Lecture-ethics.webp": [
    768,
    576
  ],
  "/images/news/copyright-ai/Avinesh_01.jpeg": [
    960,
    1280
  ],
  "/images/news/gender-equality-02.webp": [
    1600,
    1200
  ],
  "/images/news/masculinity/Masculinity_01.jpg": [
    815,
    615
  ],
  "/images/news/student1.webp": [
    1333,
    861
  ],
  "/images/schlorship/01.webp": [
    752,
    520
  ],
  "/images/shall1.webp": [
    380,
    381
  ],
  "/images/studentaff/1.webp": [
    1200,
    600
  ],
  "/images/studentaff/moot.webp": [
    324,
    394
  ],
  "/images/studentaff/sports.webp": [
    324,
    394
  ],
  "/images/studentaff/thumbnail.webp": [
    330,
    180
  ],
  "/images/vmls/frame-1@3x.webp": [
    1600,
    900
  ],
  "/images/vmls/vmls-arch.png": [
    1024,
    1024
  ],
  "/images/vmrf/Frame-53135.webp": [
    263,
    246
  ],
  "/images/vmrf/Frame-53136.webp": [
    263,
    246
  ],
  "/images/vmrf/bg-chancellor.png": [
    792,
    437
  ],
  "/images/vmrf/vmrf-header.webp": [
    1920,
    864
  ]
};
