// AUTO-GENERATED by scripts/generate-redirects.mjs - do not edit by hand.
// 301 map from the previous static site (vmls.edu.in/*.html) to this app.
// Regenerate:  node scripts/generate-redirects.mjs <live-urls.txt>
export type Redirect = { source: string; destination: string; permanent: boolean };

export const REDIRECTS: Redirect[] = [
  {
    "source": "/blogs.html",
    "destination": "/blogs",
    "permanent": true
  },
  {
    "source": "/blogs/aibe-all-india-bar-exam-guide.html",
    "destination": "/blogs/aibe-all-india-bar-exam-guide",
    "permanent": true
  },
  {
    "source": "/blogs/what-does-bci-approval-mean-law-college.html",
    "destination": "/blogs/what-does-bci-approval-mean-law-college",
    "permanent": true
  },
  {
    "source": "/blogs/clat-2027-exam-dates-eligibility-syllabus-and-admission.html",
    "destination": "/blogs/clat-2027-exam-dates-eligibility-syllabus-and-admission",
    "permanent": true
  },
  {
    "source": "/mentoring-committee/dr-padmanabha-ramanunjam",
    "destination": "/mentoring-committee",
    "permanent": true
  },
  {
    "source": "/faculty/s-suganya",
    "destination": "/faculty-profiles",
    "permanent": true
  },
  {
    "source": "/faculty/tathagat-sharma",
    "destination": "/faculty-profiles",
    "permanent": true
  },
  {
    "source": "/faculty/kiran-jenifer",
    "destination": "/faculty-profiles",
    "permanent": true
  },
  {
    "source": "/blogs/full-time-phd-in-law-and-interdisciplinary-studies.html",
    "destination": "/blogs/full-time-phd-in-law-and-interdisciplinary-studies",
    "permanent": true
  },
  {
    "source": "/blogs/part-time-phd-in-law-and-interdisciplinary-studies.html",
    "destination": "/blogs/part-time-phd-in-law-and-interdisciplinary-studies",
    "permanent": true
  },
  {
    "source": "/blogs/clat-2026-exam-dates-eligibility-syllabus-and-admission.html",
    "destination": "/blogs/clat-2026-exam-dates-eligibility-syllabus-and-admission",
    "permanent": true
  },
  {
    "source": "/blogs/vmls-open-day-2025.html",
    "destination": "/blogs/vmls-open-day-2025",
    "permanent": true
  },
  {
    "source": "/blogs/vmrf-law-admission-test-vlat.html",
    "destination": "/blogs/vmrf-law-admission-test-vlat",
    "permanent": true
  },
  {
    "source": "/blogs/vmrf-law-aptitude-test-vlat.html",
    "destination": "/blogs/vmrf-law-aptitude-test-vlat",
    "permanent": true
  },
  {
    "source": "/blogs/scholarships-for-law-students-in-india.html",
    "destination": "/blogs/scholarships-for-law-students-in-india",
    "permanent": true
  },
  {
    "source": "/blogs/how-to-become-a-judge-in-india-after-llb.html",
    "destination": "/blogs/how-to-become-a-judge-in-india-after-llb",
    "permanent": true
  },
  {
    "source": "/blogs/career-after-llb-litigation-vs-corporate-vs-judiciary.html",
    "destination": "/blogs/career-after-llb-litigation-vs-corporate-vs-judiciary",
    "permanent": true
  },
  {
    "source": "/blogs/how-to-prepare-for-vlat-study-plan.html",
    "destination": "/blogs/how-to-prepare-for-vlat-study-plan",
    "permanent": true
  },
  {
    "source": "/blogs/llb-fees-in-india-complete-cost-breakdown.html",
    "destination": "/blogs/llb-fees-in-india-complete-cost-breakdown",
    "permanent": true
  },
  {
    "source": "/international-conference",
    "destination": "/international-conference-on-rivers",
    "permanent": true
  },
  {
    "source": "/membership.html",
    "destination": "/library-membership",
    "permanent": true
  },
  {
    "source": "/membership",
    "destination": "/library-membership",
    "permanent": true
  },
  {
    "source": "/rules-and-regulations.html",
    "destination": "/library-rules",
    "permanent": true
  },
  {
    "source": "/rules-and-regulations",
    "destination": "/library-rules",
    "permanent": true
  },
  {
    "source": "/library-useful-links.html",
    "destination": "/library-useful-links",
    "permanent": true
  },
  {
    "source": "/library.html",
    "destination": "/library",
    "permanent": true
  },
  {
    "source": "/student-affairs.html",
    "destination": "/student-affairs",
    "permanent": true
  },
  {
    "source": "/clubs-at-vinayaka-missions-law-school.html",
    "destination": "/student-clubs",
    "permanent": true
  },
  {
    "source": "/clubs-at-vinayaka-missions-law-school",
    "destination": "/student-clubs",
    "permanent": true
  },
  {
    "source": "/help/anti-ragging-squad.html",
    "destination": "/anti-ragging-squad",
    "permanent": true
  },
  {
    "source": "/help/anti-ragging-squad",
    "destination": "/anti-ragging-squad",
    "permanent": true
  },
  {
    "source": "/news/aarambh-the-freshers-fiesta.html",
    "destination": "/news/aarambh-fiesta",
    "permanent": true
  },
  {
    "source": "/news/vmls-fest-2025-two-days-infinite-vibes-one-unforgettable-experience.html",
    "destination": "/news/vmls-fest-2025",
    "permanent": true
  },
  {
    "source": "/news/lspl-where-law-meets-football-and-unity-scores-big.html",
    "destination": "/news/lspl",
    "permanent": true
  },
  {
    "source": "/news/students-secures-award-at-international-conference-on-women-and-ai.html",
    "destination": "/news/women-and-ai-conference",
    "permanent": true
  },
  {
    "source": "/blogs/corporate-law-courses-in-india-degrees-eligibility-salary.html",
    "destination": "/blogs/corporate-law-courses-in-india-degrees-eligibility-salary",
    "permanent": true
  },
  {
    "source": "/blogs/criminal-law-in-chennai-curriculum-degrees-careers.html",
    "destination": "/blogs/criminal-law-in-chennai-curriculum-degrees-careers",
    "permanent": true
  },
  {
    "source": "/blogs/india-anti-paper-leak-law-2026-explained.html",
    "destination": "/blogs/india-anti-paper-leak-law-2026-explained",
    "permanent": true
  },
  {
    "source": "/blogs/third-party-litigation-funding-india-guide.html",
    "destination": "/blogs/third-party-litigation-funding-india-guide",
    "permanent": true
  },
  {
    "source": "/blogs/tribunals-reforms-bill-2026-national-tribunals-commission.html",
    "destination": "/blogs/tribunals-reforms-bill-2026-national-tribunals-commission",
    "permanent": true
  },
  {
    "source": "/blogs/personality-rights-india-ai-deepfakes-law.html",
    "destination": "/blogs/personality-rights-india-ai-deepfakes-law",
    "permanent": true
  },
  {
    "source": "/blogs/supreme-court-handbook-judgments-gender-explained.html",
    "destination": "/blogs/supreme-court-handbook-judgments-gender-explained",
    "permanent": true
  },
  {
    "source": "/vmls-open-day-2026.html",
    "destination": "/blogs/vmls-open-day-2026",
    "permanent": true
  },
  {
    "source": "/About-VMRF.html",
    "destination": "/about-vmrf",
    "permanent": true
  },
  {
    "source": "/Scholarships.html",
    "destination": "/scholarships",
    "permanent": true
  },
  {
    "source": "/about.html",
    "destination": "/about-vmls",
    "permanent": true
  },
  {
    "source": "/assets/images/Newsletter-feb-march-2026.pdf",
    "destination": "/images/newsletter/Newsletter-feb-march-2026.pdf",
    "permanent": true
  },
  {
    "source": "/atrium.html",
    "destination": "/atrium",
    "permanent": true
  },
  {
    "source": "/blogs/3-year-llb-programme-india-2026.html",
    "destination": "/blogs/3-year-llb-programme-india-2026",
    "permanent": true
  },
  {
    "source": "/blogs/5-year-integrated-llb-programme-india-2026.html",
    "destination": "/blogs/5-year-integrated-llb-programme-india-2026",
    "permanent": true
  },
  {
    "source": "/blogs/ba-llb-hons-programme-2026.html",
    "destination": "/blogs/ba-llb-hons-programme-2026",
    "permanent": true
  },
  {
    "source": "/blogs/bba-llb-colleges-in-india-2026.html",
    "destination": "/blogs/bba-llb-colleges-in-india-2026",
    "permanent": true
  },
  {
    "source": "/blogs/best-law-colleges-in-india-2026.html",
    "destination": "/blogs/best-law-colleges-in-india-2026",
    "permanent": true
  },
  {
    "source": "/blogs/bilingual-law-school-chennai-2026.html",
    "destination": "/blogs/bilingual-law-school-chennai-2026",
    "permanent": true
  },
  {
    "source": "/blogs/law-courses-after-graduation-2026.html",
    "destination": "/blogs/law-courses-after-graduation-2026",
    "permanent": true
  },
  {
    "source": "/blogs/llb-admission-2026.html",
    "destination": "/blogs/llb-admission-2026",
    "permanent": true
  },
  {
    "source": "/blogs/llb-fees-india-2026-27.html",
    "destination": "/blogs/llb-fees-india-2026-27",
    "permanent": true
  },
  {
    "source": "/blogs/bcom-llb-colleges-india-2026-27.html",
    "destination": "/blogs/bcom-llb-colleges-india-2026-27",
    "permanent": true
  },
  {
    "source": "/blogs/llm-corporate-law-career-scope-2026-27.html",
    "destination": "/blogs/llm-corporate-law-career-scope-2026-27",
    "permanent": true
  },
  {
    "source": "/blogs/how-to-choose-the-right-law-university-india.html",
    "destination": "/blogs/how-to-choose-the-right-law-university-india",
    "permanent": true
  },
  {
    "source": "/blogs/llb-admission-dates-process-checklist-2026-27.html",
    "destination": "/blogs/llb-admission-dates-process-checklist-2026-27",
    "permanent": true
  },
  {
    "source": "/blogs/3-year-llb-vs-5-year-llb-comparison.html",
    "destination": "/blogs/3-year-llb-vs-5-year-llb-comparison",
    "permanent": true
  },
  {
    "source": "/blogs/3-year-llb-admission-chennai-tamilnadu.html",
    "destination": "/blogs/3-year-llb-admission-chennai-tamilnadu",
    "permanent": true
  },
  {
    "source": "/blogs/llm-specializations-guide-colleges-chennai.html",
    "destination": "/blogs/llm-specializations-guide-colleges-chennai",
    "permanent": true
  },
  {
    "source": "/blogs/ba-llb-vs-bba-llb-vs-bcom-llb-comparison.html",
    "destination": "/blogs/ba-llb-vs-bba-llb-vs-bcom-llb-comparison",
    "permanent": true
  },
  {
    "source": "/blogs/law-entrance-exams-clat-vs-vlat-comparison.html",
    "destination": "/blogs/law-entrance-exams-clat-vs-vlat-comparison",
    "permanent": true
  },
  {
    "source": "/blogs/top-law-colleges-india.html",
    "destination": "/blogs/top-law-colleges-india",
    "permanent": true
  },
  {
    "source": "/blogs/vmls-open-day-2026.html",
    "destination": "/blogs/vmls-open-day-2026",
    "permanent": true
  },
  {
    "source": "/blogs/ba-llb-admission-2026-eligibility-application-process-fees-career-opportunities.html",
    "destination": "/blogs/ba-llb-admission-2026-eligibility-application-process-fees-career-opportunities",
    "permanent": true
  },
  {
    "source": "/blogs/ba-llb-course-in-india-eligibility-fees-duration-best-law-colleges.html",
    "destination": "/blogs/ba-llb-course-in-india-eligibility-fees-duration-best-law-colleges",
    "permanent": true
  },
  {
    "source": "/blogs/bachelors-degree-in-law.html",
    "destination": "/blogs/bachelors-degree-in-law",
    "permanent": true
  },
  {
    "source": "/blogs/law-entrance-exam-vlat.html",
    "destination": "/blogs/law-entrance-exam-vlat",
    "permanent": true
  },
  {
    "source": "/blogs/law-entrance-exams-in-india-2026-complete-guide.html",
    "destination": "/blogs/law-entrance-exams-in-india-2026-complete-guide",
    "permanent": true
  },
  {
    "source": "/blogs/llm-eligibility-requirements-for-master-of-laws-admission.html",
    "destination": "/blogs/llm-eligibility-requirements-for-master-of-laws-admission",
    "permanent": true
  },
  {
    "source": "/blogs/llm-entrance-exam-india-2026-27.html",
    "destination": "/blogs/llm-entrance-exam-india-2026-27",
    "permanent": true
  },
  {
    "source": "/blogs/llm-programme-in-india-2026-27.html",
    "destination": "/blogs/llm-programme-in-india-2026-27",
    "permanent": true
  },
  {
    "source": "/blogs/the-best-law-colleges-in-india.html",
    "destination": "/blogs/the-best-law-colleges-in-india",
    "permanent": true
  },
  {
    "source": "/blogs/top-law-college-in-chennai-for-llb-llm-ph-d-admissions.html",
    "destination": "/blogs/top-law-college-in-chennai-for-llb-llm-ph-d-admissions",
    "permanent": true
  },
  {
    "source": "/blogs/top-law-colleges-in-tamil-nadu.html",
    "destination": "/blogs/top-law-colleges-in-tamil-nadu",
    "permanent": true
  },
  {
    "source": "/blogs/top-llm-colleges-in-india-2026-27.html",
    "destination": "/blogs/top-llm-colleges-in-india-2026-27",
    "permanent": true
  },
  {
    "source": "/centre-for-access-to-justice.html",
    "destination": "/centre-for-access-to-justice",
    "permanent": true
  },
  {
    "source": "/centre-for-justice-through-technology.html",
    "destination": "/centre-for-justice-through-technology",
    "permanent": true
  },
  {
    "source": "/centre-for-maritime-law.html",
    "destination": "/maritime-law",
    "permanent": true
  },
  {
    "source": "/centre-for-the-promotion-of-international-law.html",
    "destination": "/cpil",
    "permanent": true
  },
  {
    "source": "/classroom.html",
    "destination": "/classroom",
    "permanent": true
  },
  {
    "source": "/deans-desk.html",
    "destination": "/dean",
    "permanent": true
  },
  {
    "source": "/faculty.html",
    "destination": "/faculty-profiles",
    "permanent": true
  },
  {
    "source": "/food-court.html",
    "destination": "/food-court",
    "permanent": true
  },
  {
    "source": "/global-tamil-law-centre.html",
    "destination": "/global-tamil-law-centre",
    "permanent": true
  },
  {
    "source": "/hostel.html",
    "destination": "/hostel",
    "permanent": true
  },
  {
    "source": "/main-building.html",
    "destination": "/main-building",
    "permanent": true
  },
  {
    "source": "/mentoring-committee.html",
    "destination": "/mentoring-committee",
    "permanent": true
  },
  {
    "source": "/moot-court.html",
    "destination": "/moot-court",
    "permanent": true
  },
  {
    "source": "/news/1st-CJT-Lecture.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/appointment-of-executive-dean.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/bhagwan-shankar-lecture-vmls.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/career-prospects-in-the-banking-sector.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/clashes-of-masculinity-urban-rural-india.html",
    "destination": "/news/clashes-of-masculinity-urban-rural-india",
    "permanent": true
  },
  {
    "source": "/news/copyright-and-emerging-issues-due-to-artificial-intelligence.html",
    "destination": "/news/copyright-and-emerging-issues-due-to-artificial-intelligence",
    "permanent": true
  },
  {
    "source": "/news/digitalization-government-legal-concerns.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/empowering-justice-legal-aid-camp-vinayaka-missions.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/first-graduation-ceremony.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/fundamental-theories-corporate-governance.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/fundamentals-constitutional-law-theory-practice.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/giec-fireside-chat.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/guest-lecture-appreciating-modern-indian-company-law-key-foundational-principles.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/guest-lecture-rera-disputes.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/inauguration-and-commencement-programme-2025-26.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/inauguration-day.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/inauguration-of-legal-aid-clinic-at-vmls.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/indias-most-promising-emerging-law-school-2025.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/lecture-corporate-commercial-laws.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/lecture-ethics-of-research.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/legal-aid-cell-orientation-program.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/legal-awareness-rally.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/legal-design-competition.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/legal-literacy-camp.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/llm-inauguration.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/lspl-season-2.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/masterclass-natasha-varyani.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/moot-court-competitions.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/mou-with-roger-williams-university-school-of-law.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/mou-with-sri-ragini-dharmasthaapanam.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/national-seminar-on-ai.html",
    "destination": "/news/national-seminar-on-ai",
    "permanent": true
  },
  {
    "source": "/news/nss-lake-cleaning-drive.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/onam-celebration-a-tapestry-of-tradition-unity-and-joy.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/one-day-life-at-vmls.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/professional-development-program-on-becoming-an-inspiring-teacher.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/research-importance-application-after-law-school.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/special-lecture-trial-advocacy-skills.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/student-immersion-program-jindal-global-law-school.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/students-won-best-presenter-awards-at-national-conference.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/the-free-legal-awareness-camp.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/vigneshwaran-k-wins-debate-competition-at-clcexcellence-2026.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/vinayaka-missions-law-school-inaugurates-2024-25-batch-with-distinguished-guests.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/virtual-panel-discussion-climate-change.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/vmls-75th-national-constitution-day.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/vmrf-signs-mou-with-k-kccs-india-to-strengthen-japan-pathways-for-students.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/seminar-halls.html",
    "destination": "/seminar-hall",
    "permanent": true
  },
  {
    "source": "/Avni-Singh-Solanki.html",
    "destination": "/faculty/avni-singh-solanki",
    "permanent": true
  },
  {
    "source": "/Dr.A.Francis-Julian.html",
    "destination": "/mentoring-committee/dr-a-francis-julian",
    "permanent": true
  },
  {
    "source": "/Dr.A.S.Ganesan.html",
    "destination": "/chancellor",
    "permanent": true
  },
  {
    "source": "/Dr.A.Shanmugasundaram.html",
    "destination": "/founder",
    "permanent": true
  },
  {
    "source": "/Dr.Anuradha-Ganesan.html",
    "destination": "/about-vmrf",
    "permanent": true
  },
  {
    "source": "/Dr.Fowmina.html",
    "destination": "/faculty/fowmina",
    "permanent": true
  },
  {
    "source": "/Dr.Gnana-Sanga-Mithra.S.html",
    "destination": "/faculty/gnana-sanga-mithra",
    "permanent": true
  },
  {
    "source": "/Dr.Padmanabha-Ramanunjam.html",
    "destination": "/mentoring-committee/dr-padmanabha-ramanujam",
    "permanent": true
  },
  {
    "source": "/Dr.Sachinkumar.html",
    "destination": "/faculty/sachinkumar-p-p",
    "permanent": true
  },
  {
    "source": "/Dr.Shenbagavalli.html",
    "destination": "/faculty/shenbagavalli",
    "permanent": true
  },
  {
    "source": "/Mr.Antony-R.Julian.html",
    "destination": "/mentoring-committee/mr-antony-r-julian",
    "permanent": true
  },
  {
    "source": "/Mr.Edhaya-Chandran.html",
    "destination": "/faculty/edhaya-chandran",
    "permanent": true
  },
  {
    "source": "/Mr.J.Suresh-Samuel.html",
    "destination": "/mentoring-committee/mr-j-suresh-samuel",
    "permanent": true
  },
  {
    "source": "/Mr.Krishna-Kishore-Padala.html",
    "destination": "/faculty/krishna-kishore-padala",
    "permanent": true
  },
  {
    "source": "/Mr.Vivek-Dhokalia.html",
    "destination": "/mentoring-committee/mr-vivek-dhokalia",
    "permanent": true
  },
  {
    "source": "/Mr.victor.html",
    "destination": "/faculty/victor",
    "permanent": true
  },
  {
    "source": "/Mr_Siddharth_raja.html",
    "destination": "/dean",
    "permanent": true
  },
  {
    "source": "/Ms.Chesha-P.Chellappan.html",
    "destination": "/faculty/chesha-p-chellappan",
    "permanent": true
  },
  {
    "source": "/Ms.Merlin-Stephen.html",
    "destination": "/faculty/merlin-stephen",
    "permanent": true
  },
  {
    "source": "/Ms.Nabeela-Siddiqui.html",
    "destination": "/faculty/nabeela-siddiqui",
    "permanent": true
  },
  {
    "source": "/Ms.Sinjini-Sen.html",
    "destination": "/faculty/sinjini-sen",
    "permanent": true
  },
  {
    "source": "/Prof.Anand-Prakash-Mishra.html",
    "destination": "/mentoring-committee/prof-anand-prakash-mishra",
    "permanent": true
  },
  {
    "source": "/Prof.Dr.C.Raj%20Kumar.html",
    "destination": "/mentoring-committee/prof-dr-c-raj-kumar",
    "permanent": true
  },
  {
    "source": "/Prof.Dr.Sreejith-S.G.html",
    "destination": "/mentoring-committee/prof-dr-sreejith-sg",
    "permanent": true
  },
  {
    "source": "/Stalin-Harikaran-N.html",
    "destination": "/faculty/stalin-harikaran-n",
    "permanent": true
  },
  {
    "source": "/abhinandita.html",
    "destination": "/faculty/abhinandita-biswas",
    "permanent": true
  },
  {
    "source": "/abhinaya-ramesh.html",
    "destination": "/faculty/abhinaya-ramesh",
    "permanent": true
  },
  {
    "source": "/abraham-s.html",
    "destination": "/faculty/abraham-s",
    "permanent": true
  },
  {
    "source": "/akshara-nair.html",
    "destination": "/faculty/akshara-nair",
    "permanent": true
  },
  {
    "source": "/ashwani-kumar-singh.html",
    "destination": "/faculty/ashwani-kumar-singh",
    "permanent": true
  },
  {
    "source": "/blogs/bringing-indian-contracts-ii-to-life-clinical-legal-education-vmls.html",
    "destination": "/blogs/bringing-indian-contracts-ii-to-life-clinical-legal-education-vmls",
    "permanent": true
  },
  {
    "source": "/blogs/lack-of-clinical-legal-education-in-india.html",
    "destination": "/blogs/lack-of-clinical-legal-education-in-india",
    "permanent": true
  },
  {
    "source": "/blogs/llm-in-artificial-intelligence-emerging-technologies-and-intellectual-property-rights.html",
    "destination": "/blogs/llm-in-artificial-intelligence-emerging-technologies-and-intellectual-property-rights",
    "permanent": true
  },
  {
    "source": "/blogs/llm-in-criminal-law-and-practice.html",
    "destination": "/blogs/llm-in-criminal-law-and-practice",
    "permanent": true
  },
  {
    "source": "/blogs/what-is-llm-master-of-law-degree.html",
    "destination": "/blogs/what-is-llm-master-of-law-degree",
    "permanent": true
  },
  {
    "source": "/dr-alisha-verma.html",
    "destination": "/faculty/alisha-verma",
    "permanent": true
  },
  {
    "source": "/dr-anuttama-ghose.html",
    "destination": "/faculty/anuttama-ghose",
    "permanent": true
  },
  {
    "source": "/dr-arun-d-raj.html",
    "destination": "/faculty/arun-d-raj",
    "permanent": true
  },
  {
    "source": "/dr-gaurav-shukla.html",
    "destination": "/faculty/gaurav-shukla",
    "permanent": true
  },
  {
    "source": "/dr-jacob-joseph.html",
    "destination": "/faculty/jacob-joseph",
    "permanent": true
  },
  {
    "source": "/dr-muthuvelu.html",
    "destination": "/faculty/muthuvelu",
    "permanent": true
  },
  {
    "source": "/dr-s-suganya.html",
    "destination": "/faculty-profiles",
    "permanent": true
  },
  {
    "source": "/dr-shabin-os.html",
    "destination": "/faculty/shabin-o-s",
    "permanent": true
  },
  {
    "source": "/dr-yazhini-a.html",
    "destination": "/faculty/yazhini-a",
    "permanent": true
  },
  {
    "source": "/hartej-singh.html",
    "destination": "/faculty/hartej-singh",
    "permanent": true
  },
  {
    "source": "/kamala-priyadarshini.html",
    "destination": "/faculty/kamala-priyadarshini",
    "permanent": true
  },
  {
    "source": "/kush-tanvani.html",
    "destination": "/faculty/kush-tanvani",
    "permanent": true
  },
  {
    "source": "/luke-jackson.html",
    "destination": "/faculty/luke-jackson",
    "permanent": true
  },
  {
    "source": "/mike-ruban.html",
    "destination": "/faculty/mike-ruban",
    "permanent": true
  },
  {
    "source": "/ms-aarthy-jonathan-kennedy.html",
    "destination": "/faculty/aarthy-jonathan-kennedy",
    "permanent": true
  },
  {
    "source": "/ms-kiran-jenifer.html",
    "destination": "/faculty-profiles",
    "permanent": true
  },
  {
    "source": "/ms-r-sneha.html",
    "destination": "/faculty/r-sneha",
    "permanent": true
  },
  {
    "source": "/narayanan-chandrasekar.html",
    "destination": "/faculty/narayanan-chandrasekar",
    "permanent": true
  },
  {
    "source": "/news/ai-for-justice-vmls-setu-law-workshop.html",
    "destination": "/news/ai-for-justice-vmls-setu-law-workshop",
    "permanent": true
  },
  {
    "source": "/news/distinguished-guest-lecture-series-law-of-the-sea.html",
    "destination": "/news/distinguished-guest-lecture-series-law-of-the-sea",
    "permanent": true
  },
  {
    "source": "/news/e-filing.html",
    "destination": "/news/e-filing",
    "permanent": true
  },
  {
    "source": "/news/flip-case-legal-design-challenge.html",
    "destination": "/news/flip-case-legal-design-challenge",
    "permanent": true
  },
  {
    "source": "/news/international-conference-on-rivers.html",
    "destination": "/news/international-conference-on-rivers",
    "permanent": true
  },
  {
    "source": "/news/international-tamil-law-conference-2025.html",
    "destination": "/news/international-tamil-law-conference-2025",
    "permanent": true
  },
  {
    "source": "/news/intra-trail-tamil-moot-court.html",
    "destination": "/news/intra-trail-tamil-moot-court",
    "permanent": true
  },
  {
    "source": "/news/maritime-law-summit-2025.html",
    "destination": "/news/maritime-law-summit-2025",
    "permanent": true
  },
  {
    "source": "/news/special-lecture-international-maritime-law.html",
    "destination": "/news/special-lecture-international-maritime-law",
    "permanent": true
  },
  {
    "source": "/news/state-level-tamil-family-law-moot-court-competition.html",
    "destination": "/news/state-level-tamil-family-law-moot-court-competition",
    "permanent": true
  },
  {
    "source": "/news/vmls-signs-mou-with-university-of-san-diego.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/news/why-international-law-matters-inaugural-session.html",
    "destination": "/news/why-international-law-matters-inaugural-session",
    "permanent": true
  },
  {
    "source": "/news/womens-hygiene-drive.html",
    "destination": "/news",
    "permanent": true
  },
  {
    "source": "/shubham-shukla.html",
    "destination": "/faculty/shubham-shukla",
    "permanent": true
  },
  {
    "source": "/sm-aamir-ali.html",
    "destination": "/faculty/aamir-ali",
    "permanent": true
  },
  {
    "source": "/sowmiya-narayan-rajagopalan.html",
    "destination": "/faculty/sowmiya-narayan-rajagopalan",
    "permanent": true
  },
  {
    "source": "/srinivas-raman.html",
    "destination": "/faculty/srinivas-raman",
    "permanent": true
  },
  {
    "source": "/tathagat-sharma.html",
    "destination": "/faculty-profiles",
    "permanent": true
  },
  {
    "source": "/winfred-chelliah.html",
    "destination": "/faculty/winfred-chelliah",
    "permanent": true
  },
  {
    "source": "/blogs/3-year-llb-programme.html",
    "destination": "/blogs/3-year-llb-programme",
    "permanent": true
  },
  {
    "source": "/blogs/5-year-llb-programme.html",
    "destination": "/blogs/5-year-llb-programme",
    "permanent": true
  },
  {
    "source": "/blogs/clat-exam-importance-eligibility-criteria-syllabus.html",
    "destination": "/blogs/clat-exam-importance-eligibility-criteria-syllabus",
    "permanent": true
  },
  {
    "source": "/blogs/clinical-legal-education-and-evidence-law-training-in-india.html",
    "destination": "/blogs/clinical-legal-education-and-evidence-law-training-in-india",
    "permanent": true
  },
  {
    "source": "/blogs/explore-diverse-career-opportunities-in-law-in-india-roles-necessary-skills-and-top-employers.html",
    "destination": "/blogs/explore-diverse-career-opportunities-in-law-in-india-roles-necessary-skills-and-top-employers",
    "permanent": true
  },
  {
    "source": "/blogs/important-component-of-clinical-legal-education.html",
    "destination": "/blogs/important-component-of-clinical-legal-education",
    "permanent": true
  },
  {
    "source": "/blogs/llm-in-commercial-dispute-resolution.html",
    "destination": "/blogs/llm-in-commercial-dispute-resolution",
    "permanent": true
  },
  {
    "source": "/blogs/llm-in-corporate-financial-laws.html",
    "destination": "/blogs/llm-in-corporate-financial-laws",
    "permanent": true
  },
  {
    "source": "/blogs/one-year-llm-programme-vmls.html",
    "destination": "/blogs/one-year-llm-programme-vmls",
    "permanent": true
  },
  {
    "source": "/blogs/subjects-in-law-courses.html",
    "destination": "/blogs/subjects-in-law-courses",
    "permanent": true
  },
  {
    "source": "/blogs/top-5-legal-careers-in-india-2025.html",
    "destination": "/blogs/top-5-legal-careers-in-india-2025",
    "permanent": true
  },
  {
    "source": "/blogs/what-is-llb-degree.html",
    "destination": "/blogs/what-is-llb-degree",
    "permanent": true
  },
  {
    "source": "/blogs/why-clinical-legal-education-in-india-is-struggling.html",
    "destination": "/blogs/why-clinical-legal-education-in-india-is-struggling",
    "permanent": true
  },
  {
    "source": "/llb-programme.html",
    "destination": "/admissions/llb",
    "permanent": true
  },
  {
    "source": "/llm-programme.html",
    "destination": "/admissions/llm",
    "permanent": true
  },
  {
    "source": "/Campus.html",
    "destination": "/campus-life",
    "permanent": true
  },
  {
    "source": "/Contact-Us.html",
    "destination": "/contact-us",
    "permanent": true
  },
  {
    "source": "/Mr.Ananyo-Mitra.html",
    "destination": "/faculty-profiles",
    "permanent": true
  },
  {
    "source": "/blog",
    "destination": "/blogs",
    "permanent": true
  },
  {
    "source": "/blog/5-year-ba-llb-hons",
    "destination": "/blogs/5-year-ba-llb-hons",
    "permanent": true
  },
  {
    "source": "/blog/5-year-bba-llb-hons",
    "destination": "/blogs/5-year-bba-llb-hons",
    "permanent": true
  },
  {
    "source": "/blog/5-year-bcom-llb-hons",
    "destination": "/blogs/5-year-bcom-llb-hons",
    "permanent": true
  },
  {
    "source": "/blog/best-time-to-apply-for-llb-admission-in-india",
    "destination": "/blogs/best-time-to-apply-for-llb-admission-in-india",
    "permanent": true
  },
  {
    "source": "/blog/category/clinical-legal-education",
    "destination": "/blogs",
    "permanent": true
  },
  {
    "source": "/blog/category/distance-ll-b",
    "destination": "/blogs",
    "permanent": true
  },
  {
    "source": "/blog/category/law-colleges-in-india",
    "destination": "/blogs",
    "permanent": true
  },
  {
    "source": "/blog/category/law-entrance-exams-in-india",
    "destination": "/blogs",
    "permanent": true
  },
  {
    "source": "/blog/category/llb",
    "destination": "/blogs",
    "permanent": true
  },
  {
    "source": "/blog/category/llb/law-courses-in-india",
    "destination": "/blogs",
    "permanent": true
  },
  {
    "source": "/blog/category/moot-court",
    "destination": "/blogs",
    "permanent": true
  },
  {
    "source": "/blog/category/news",
    "destination": "/blogs",
    "permanent": true
  },
  {
    "source": "/blog/category/vlat",
    "destination": "/blogs",
    "permanent": true
  },
  {
    "source": "/blog/common-mistakes-students-make-during-the-llb-admission-process",
    "destination": "/blogs/common-mistakes-students-make-during-the-llb-admission-process",
    "permanent": true
  },
  {
    "source": "/blog/step-by-step-guide-to-law-college-admission",
    "destination": "/blogs/step-by-step-guide-to-law-college-admission",
    "permanent": true
  },
  {
    "source": "/blog/the-best-law-college-for-bengaluru-students",
    "destination": "/blogs/the-best-law-college-for-bengaluru-students",
    "permanent": true
  },
  {
    "source": "/blog/three-year-llb-hons",
    "destination": "/blogs/three-year-llb-hons",
    "permanent": true
  },
  {
    "source": "/blogs/best-law-courses-after-12th.html",
    "destination": "/blogs/best-law-courses-after-12th",
    "permanent": true
  },
  {
    "source": "/blogs/beyond-the-classroom-clinical-legal-education-promise.html",
    "destination": "/blogs/beyond-the-classroom-clinical-legal-education-promise",
    "permanent": true
  },
  {
    "source": "/blogs/black-carbon-and-the-law-response.html",
    "destination": "/blogs/black-carbon-and-the-law-response",
    "permanent": true
  },
  {
    "source": "/blogs/cle-impact-on-healthcare-laws-and-patients-rights-in-india.html",
    "destination": "/blogs/cle-impact-on-healthcare-laws-and-patients-rights-in-india",
    "permanent": true
  },
  {
    "source": "/blogs/climate-finance-development-in-india-cop29.html",
    "destination": "/blogs/climate-finance-development-in-india-cop29",
    "permanent": true
  },
  {
    "source": "/blogs/clinical-education-in-financial-frauds-white-collar-crimes.html",
    "destination": "/blogs/clinical-education-in-financial-frauds-white-collar-crimes",
    "permanent": true
  },
  {
    "source": "/blogs/clinical-legal-education-in-india.html",
    "destination": "/blogs/clinical-legal-education-in-india",
    "permanent": true
  },
  {
    "source": "/blogs/clinical-legal-education-justice-for-marginalized.html",
    "destination": "/blogs/clinical-legal-education-justice-for-marginalized",
    "permanent": true
  },
  {
    "source": "/blogs/criminal-law-and-forensics-how-cle-shapes-legal-practice.html",
    "destination": "/blogs/criminal-law-and-forensics-how-cle-shapes-legal-practice",
    "permanent": true
  },
  {
    "source": "/blogs/decoding-competition-law-the-cle-approach.html",
    "destination": "/blogs/decoding-competition-law-the-cle-approach",
    "permanent": true
  },
  {
    "source": "/blogs/empowering-future-advocates-clinical-legal-education-initiative-at-vmls.html",
    "destination": "/blogs/empowering-future-advocates-clinical-legal-education-initiative-at-vmls",
    "permanent": true
  },
  {
    "source": "/blogs/empowering-women-through-clinical-legal-education-in-india.html",
    "destination": "/blogs/empowering-women-through-clinical-legal-education-in-india",
    "permanent": true
  },
  {
    "source": "/blogs/ex-ante-regulation.html",
    "destination": "/blogs/ex-ante-regulation",
    "permanent": true
  },
  {
    "source": "/blogs/fostering-legal-skills-and-advancing-social-justice-through-cle.html",
    "destination": "/blogs/fostering-legal-skills-and-advancing-social-justice-through-cle",
    "permanent": true
  },
  {
    "source": "/blogs/future-human-rights-advocates-clinical-legal-education.html",
    "destination": "/blogs/future-human-rights-advocates-clinical-legal-education",
    "permanent": true
  },
  {
    "source": "/blogs/global-perspective-clinical-legal-education.html",
    "destination": "/blogs/global-perspective-clinical-legal-education",
    "permanent": true
  },
  {
    "source": "/blogs/how-clinical-legal-education-enhances-management-disciplines.html",
    "destination": "/blogs/how-clinical-legal-education-enhances-management-disciplines",
    "permanent": true
  },
  {
    "source": "/blogs/how-deepseeks-ai-is-shaping-litigation-support.html",
    "destination": "/blogs/how-deepseeks-ai-is-shaping-litigation-support",
    "permanent": true
  },
  {
    "source": "/blogs/indus-waters-treaty-suspension-lessons-for-law-students.html",
    "destination": "/blogs/indus-waters-treaty-suspension-lessons-for-law-students",
    "permanent": true
  },
  {
    "source": "/blogs/justice-at-the-grassroots-clinical-legal-education-and-family-law-practice-in-india.html",
    "destination": "/blogs/justice-at-the-grassroots-clinical-legal-education-and-family-law-practice-in-india",
    "permanent": true
  },
  {
    "source": "/blogs/law-and-economics-in-clinical-legal-education-recasting-experiential-learning-in-the-5-year-llb-program.html",
    "destination": "/blogs/law-and-economics-in-clinical-legal-education-recasting-experiential-learning-in-the-5-year-llb-program",
    "permanent": true
  },
  {
    "source": "/blogs/law-in-practice-civil-procedure-learning-in-chennai-through-clinical-legal-education.html",
    "destination": "/blogs/law-in-practice-civil-procedure-learning-in-chennai-through-clinical-legal-education",
    "permanent": true
  },
  {
    "source": "/blogs/mediation-for-operational-creditors.html",
    "destination": "/blogs/mediation-for-operational-creditors",
    "permanent": true
  },
  {
    "source": "/blogs/merger-regulations-expansion-competition-developing-economies.html",
    "destination": "/blogs/merger-regulations-expansion-competition-developing-economies",
    "permanent": true
  },
  {
    "source": "/blogs/need-for-environmental-law-clinics-in-india.html",
    "destination": "/blogs/need-for-environmental-law-clinics-in-india",
    "permanent": true
  },
  {
    "source": "/blogs/network-effects-competition-law-digital-markets.html",
    "destination": "/blogs/network-effects-competition-law-digital-markets",
    "permanent": true
  },
  {
    "source": "/blogs/sebi-tightens-rules-for-futures-options-trading.html",
    "destination": "/blogs/sebi-tightens-rules-for-futures-options-trading",
    "permanent": true
  },
  {
    "source": "/blogs/shaping-legal-futures-cle-and-constitutional-law.html",
    "destination": "/blogs/shaping-legal-futures-cle-and-constitutional-law",
    "permanent": true
  },
  {
    "source": "/blogs/top-bilingual-law-schools-in-chennai.html",
    "destination": "/blogs/top-bilingual-law-schools-in-chennai",
    "permanent": true
  },
  {
    "source": "/blogs/types-of-law-courses-in-india.html",
    "destination": "/blogs/types-of-law-courses-in-india",
    "permanent": true
  },
  {
    "source": "/blogs/vinayaka-missions-law-admission-test-VLAT.html",
    "destination": "/blogs/vinayaka-missions-law-admission-test-VLAT",
    "permanent": true
  },
  {
    "source": "/blogs/what-is-corporate-law.html",
    "destination": "/blogs/what-is-corporate-law",
    "permanent": true
  },
  {
    "source": "/blogs/what-is-financial-law.html",
    "destination": "/blogs/what-is-financial-law",
    "permanent": true
  },
  {
    "source": "/blogs/why-clinical-legal-education-and-adr-are-crucial-for-indian-justice.html",
    "destination": "/blogs/why-clinical-legal-education-and-adr-are-crucial-for-indian-justice",
    "permanent": true
  },
  {
    "source": "/blogs/why-sharing-your-childs-exam-results-online-can-impact-their-future.html",
    "destination": "/blogs/why-sharing-your-childs-exam-results-online-can-impact-their-future",
    "permanent": true
  },
  {
    "source": "/how-to-apply.html",
    "destination": "/admissions/process",
    "permanent": true
  },
  {
    "source": "/Mr.Saravanan-R.html",
    "destination": "/faculty-profiles",
    "permanent": true
  },
  {
    "source": "/blog/category/llb/page/2",
    "destination": "/blogs",
    "permanent": true
  },
  {
    "source": "/blog/empowering-migrant-labourers-in-chennai-through-clinical-legal-education-and-access-to-justice",
    "destination": "/blogs/empowering-migrant-labourers-in-chennai-through-clinical-legal-education-and-access-to-justice",
    "permanent": true
  },
  {
    "source": "/blog/from-silence-to-recognition-why-recognising-menstrual-dignity-as-a-constitutional-right-was-long-overdue",
    "destination": "/blogs/from-silence-to-recognition-why-recognising-menstrual-dignity-as-a-constitutional-right-was-long-overdue",
    "permanent": true
  },
  {
    "source": "/blog/llb-hons-eligibility-admissions-syllabus",
    "destination": "/blogs/llb-hons-eligibility-admissions-syllabus",
    "permanent": true
  },
  {
    "source": "/blog/page/2",
    "destination": "/blogs",
    "permanent": true
  },
  {
    "source": "/blog/page/3",
    "destination": "/blogs",
    "permanent": true
  },
  {
    "source": "/blog/vinayaka-missions-law-school-signs-international-mou-with-university-of-san-diego-expanding-global-learning-opportunities",
    "destination": "/blogs/vinayaka-missions-law-school-signs-international-mou-with-university-of-san-diego-expanding-global-learning-opportunities",
    "permanent": true
  },
  {
    "source": "/blog/what-is-a-moot-court",
    "destination": "/blogs/what-is-a-moot-court",
    "permanent": true
  },
  {
    "source": "/blog/why-distance-ll-b-degrees-are-not-approved-in-india",
    "destination": "/blogs/why-distance-ll-b-degrees-are-not-approved-in-india",
    "permanent": true
  },
  {
    "source": "/dr-kannan-kunnathully.html",
    "destination": "/faculty-profiles",
    "permanent": true
  },
  {
    "source": "/ms-rudra-chandran-l.html",
    "destination": "/faculty-profiles",
    "permanent": true
  },
  {
    "source": "/privacy-policy.html",
    "destination": "/privacy-policy",
    "permanent": true
  },
  {
    "source": "/terms-conditions.html",
    "destination": "/terms-conditions",
    "permanent": true
  },
  {
    "source": "/blogs/moot-court-law-school-why-it-matters.html",
    "destination": "/blogs/moot-court-law-school-why-it-matters",
    "permanent": true
  },
  {
    "source": "/blogs/law-school-internships-year-by-year-guide.html",
    "destination": "/blogs/law-school-internships-year-by-year-guide",
    "permanent": true
  },
  {
    "source": "/blogs/global-exposure-indian-law-schools-mentorship.html",
    "destination": "/blogs/global-exposure-indian-law-schools-mentorship",
    "permanent": true
  }
];
